import test from "node:test";
import assert from "node:assert/strict";
import { AudioDirector } from "../dist/audio.mjs";

class Node { constructor() { this.gain = { value: 0, setValueAtTime(){}, exponentialRampToValueAtTime(){}, setTargetAtTime(){} }; this.frequency = { value: 0, setValueAtTime(){}, exponentialRampToValueAtTime(){} }; } connect(){} disconnect(){} start(){} stop(){ this.onended?.(); } }
class Context { constructor(){ this.state="running"; this.currentTime=0; this.sampleRate=8000; this.destination={}; } createGain(){return new Node()} createDynamicsCompressor(){return new Node()} createOscillator(){return new Node()} createBufferSource(){return new Node()} createBiquadFilter(){return new Node()} createBuffer(){return {getChannelData:()=>new Float32Array(8)}} async resume(){this.state="running"} }
const event = (seq, weapon="cannon", t=seq/60) => ({ seq, t, kind:"fire", side:seq%2, moduleUid:seq, weapon, x:0, y:0, h:0 });
test("sequenced events are consumed once, including identical simultaneous weapons", async () => { const a=new AudioDirector({AudioContext:Context}); a.setPreference({enabled:true}); await a.resumeFromGesture(); a.ingest([event(1),event(2)]); a.drain(); assert.equal(a.stats.consumed,2); a.ingest([event(2),event(3)]); a.drain(); assert.equal(a.stats.consumed,3); assert.equal(a.stats.duplicate,1); });
test("accelerated gatling bursts are deliberately coalesced and queue/voice caps are accounted", async () => { const a=new AudioDirector({AudioContext:Context,maxQueue:3,maxVoices:0}); a.setPreference({enabled:true}); await a.resumeFromGesture(); const burst=[event(1,"gatling",1),event(2,"gatling",1.01),event(3,"gatling",1.02),event(4,"gatling",1.03)].map(e=>({...e,side:0})); a.ingest(burst); a.drain({speed:4}); assert.equal(a.stats.received,4); assert.equal(a.stats.dropped,3); assert.equal(a.stats.coalesced,2); assert.equal(a.stats.consumed,1); });
test("mute, suspension, and battle restart discard backlog instead of replaying stale combat", async () => { const a=new AudioDirector({AudioContext:Context}); a.setPreference({enabled:true}); await a.resumeFromGesture(); a.ingest([event(1)]); a.setPreference({enabled:false}); assert.equal(a.queue.length,0); a.setPreference({enabled:true}); a.context.state="suspended"; a.ingest([event(2)]); assert.equal(a.stats.stale,2); a.reset(); assert.equal(a.lastSeq,0); assert.equal(a.queue.length,0); });
