import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,readdirSync,unlinkSync,rmdirSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {Store,canonicalBlueprint,ENGINE_HASH} from '../server/store.mjs';
import {startServer} from '../server.mjs';
import {packChallenge,PRESETS,DEFAULT_RULES,clone} from '../dist/data.mjs';
import {Battle} from '../dist/engine.mjs';
import {hashSimulationSources} from '../server/simulation-hash.mjs';
import {CLIENT_ENGINE_HASH} from '../dist/release.mjs';

test('browser release stamp identifies the exact authoritative simulation files',()=>assert.equal(CLIENT_ENGINE_HASH,ENGINE_HASH));

const blueprint=()=>packChallenge(PRESETS[0],'foundry',0);
const body=(extra={})=>({title:'Test contract',blueprint:blueprint(),entry:10,reward:100,maxPlatformFeeBps:250,hours:24,listed:false,...extra});
function fixture(t,options={}){const s=new Store(':memory:',{seed:false,...options});t.after(()=>s.close());const owner=s.session({name:'Owner'}),entrant=s.session({name:'Challenger'});return {s,owner:owner.me.id,entrant:entrant.me.id,auth:s.auth(owner.token),entryAuth:s.auth(entrant.token)};}
const enter=(s,a,b,key=randomUUID(),extra={})=>s.accept(a,b,{blueprint:blueprint(),maxEntry:10,maxPlatformFeeBps:250,...extra},key);
const result=(job,winner)=>({winner,time:20,seed:job.seed,reason:'Test worker result',integrity:[.8,.3],damage:[600,200],mode:'auto'});

test('reward reservation, creation retry, and cancellation keep one ledger operation',t=>{const {s,owner,auth}=fixture(t),key=randomUUID(),input=body(),b=s.create(owner,input,key);assert.equal(s.me(owner).balance,900);assert.equal(s.me(owner).reserved,100);assert.equal(s.list().length,0);assert.equal(s.list(owner).length,1);assert.equal(s.create(owner,input,key).id,b.id);assert.throws(()=>s.create(owner,body({reward:200}),key),/different request/);s.cancel(auth,b.id);s.cancel(auth,b.id);assert.equal(s.me(owner).balance,1000);assert.equal(s.me(owner).reserved,0);assert.equal(s.ledger(owner).filter(l=>l.kind==='release').length,1);});
test('one official attempt holds the bounty; duplicate retry never charges twice',t=>{const {s,owner,entrant}=fixture(t),b=s.create(owner,body(),randomUUID()),key=randomUUID(),a=enter(s,entrant,b.id,key),other=s.session({name:'Other'}).me.id;assert.equal(enter(s,entrant,b.id,key).id,a.id);assert.throws(()=>enter(s,other,b.id),/busy or closed/);assert.equal(s.me(entrant).balance,990);assert.equal(s.me(other).balance,1000);assert.equal(s.bounty(b.id).status,'busy');assert.throws(()=>s.attempt(a.id,other),/private/);});
test('win pays the funded reward exactly once; public receipt includes immutable replay',t=>{const {s,owner,entrant}=fixture(t),b=s.create(owner,body(),randomUUID()),a=enter(s,entrant,b.id),job=s.claim();assert.equal(s.finish(job,result(job,0)),true);assert.equal(s.finish(job,result(job,0)),false);assert.equal(s.me(entrant).balance,1087.5);assert.equal(s.me(owner).balance,900);assert.equal(s.bounty(b.id).status,'claimed');const receipt=s.attempt(a.id);assert.equal(receipt.result.net,87.5);assert.equal(receipt.replay.seed,job.seed);assert.equal(receipt.replay.versions.hash,ENGINE_HASH);assert.throws(()=>enter(s,entrant,b.id),/closed/);});
for(const outcome of [1,-1])test(`${outcome===1?'loss':'draw'} consumes entry and reopens the same funded contract`,t=>{const {s,owner,entrant}=fixture(t),b=s.create(owner,body(),randomUUID());enter(s,entrant,b.id);const job=s.claim();s.finish(job,result(job,outcome));assert.equal(s.me(entrant).balance,990);assert.equal(s.bounty(b.id).status,'open');assert.equal(s.bounty(b.id).funded,true);assert.equal(s.me(owner).reserved,100);});
test('technical failure refunds once and restores spending allowance',t=>{const {s,owner,entrant}=fixture(t),b=s.create(owner,body(),randomUUID());enter(s,entrant,b.id);assert.equal(s.me(entrant).spentToday,10);const job=s.claim();s.finish(job,null,'Test failure');s.finish(job,null,'Test failure');assert.equal(s.me(entrant).balance,1000);assert.equal(s.me(entrant).spentToday,0);assert.equal(s.bounty(b.id).status,'open');assert.equal(s.ledger(entrant).filter(l=>l.kind==='refund').length,1);});
test('expired idle rewards return; active attempts settle even across expiry',t=>{let now=1780000000000;const {s,owner,entrant}=fixture(t,{now:()=>now}),b=s.create(owner,body({hours:1}),randomUUID());enter(s,entrant,b.id);now+=3600001;s.expire();assert.equal(s.bounty(b.id).status,'busy');const job=s.claim();s.finish(job,result(job,1));assert.equal(s.bounty(b.id).status,'expired');assert.equal(s.me(owner).balance,1000);assert.equal(s.me(entrant).balance,990);});
test('winner accepted before expiry still receives the reserved reward',t=>{let now=1780000000000;const {s,owner,entrant}=fixture(t,{now:()=>now}),b=s.create(owner,body({hours:1}),randomUUID());enter(s,entrant,b.id);const job=s.claim();now+=3600001;s.expire();s.finish(job,result(job,0));assert.equal(s.bounty(b.id).status,'claimed');assert.equal(s.me(entrant).balance,1087.5);assert.equal(s.me(owner).balance,900);});
test('spending caps, self-claims and insufficient reserves reject before any debit',t=>{const {s,owner,entrant,entryAuth}=fixture(t);assert.throws(()=>s.create(owner,body({reward:1001}),randomUUID()),/Not enough/);const b=s.create(owner,body(),randomUUID());assert.throws(()=>enter(s,owner,b.id),/own bounty/);s.settings(entryAuth,{entryCap:5});assert.throws(()=>enter(s,entrant,b.id),/per-attempt/);s.settings(entryAuth,{entryCap:100,dailyCap:10});enter(s,entrant,b.id);const job=s.claim();s.finish(job,result(job,1));assert.throws(()=>enter(s,entrant,b.id),/daily/);assert.equal(s.me(entrant).balance,990);});
test('free attempts work at zero spending caps',t=>{const {s,owner,entrant,entryAuth}=fixture(t),b=s.create(owner,body({entry:0}),randomUUID());s.settings(entryAuth,{entryCap:0,dailyCap:0});enter(s,entrant,b.id);assert.equal(s.me(entrant).balance,1000);const job=s.claim();s.finish(job,result(job,0));assert.equal(s.me(entrant).balance,1097.5);});
test('hostile client results, invalid blueprints and changed caps are rejected',t=>{const {s,owner,entrant}=fixture(t),b=s.create(owner,body(),randomUUID());assert.throws(()=>enter(s,entrant,b.id,randomUUID(),{winner:0}),/Unknown field/);const p=blueprint();p.q={...DEFAULT_RULES,mode:'unlimited',credits:null,parts:null,mass:null,weapons:null};p.b=0;p.m=[...p.m,...p.m];assert.throws(()=>enter(s,entrant,b.id,randomUUID(),{blueprint:p}),/Overlapping/);const low={...DEFAULT_RULES,mode:'custom',credits:600};assert.throws(()=>s.create(owner,body({blueprint:packChallenge(PRESETS[0],'foundry',0,low)}),randomUUID()),/Over budget/);assert.equal(s.me(entrant).balance,1000);});
test('unlimited and custom construction rules survive creation and sharing',t=>{const {s,owner}=fixture(t);for(const mode of ['unlimited','custom']){const rules={...DEFAULT_RULES,mode,credits:800,parts:24,mass:240,weapons:5},p=packChallenge(PRESETS[0],'reservoir',123,rules),b=s.create(owner,body({blueprint:p}),randomUUID());assert.equal(b.blueprint.q.mode,mode);assert.equal(b.blueprint.q.credits,mode==='unlimited'?null:800);assert.equal(b.blueprint.a,'reservoir');assert.equal(b.blueprint.e,0);assert.deepEqual(b.blueprint.m,p.m);}});
test('agent keys can cancel their own contracts but cannot raise caps or create credentials',t=>{const {s,auth,owner}=fixture(t),issued=s.agents(auth,{name:'Agent'}),agent=s.auth(issued.token);assert.equal(agent.account,owner);assert.throws(()=>s.settings(agent,{dailyCap:10000}),/owner key/);assert.throws(()=>s.agents(agent,{name:'Other'}),/owner key/);const b=s.create(owner,body(),randomUUID());assert.equal(s.cancel(agent,b.id).status,'cancelled');s.revoke(auth,s.agents(auth)[0].id);assert.throws(()=>s.auth(issued.token),/revoked/);});
test('worker lease fencing ignores old completion and recovery keeps the same seed',t=>{let now=1780000000000;const {s,owner,entrant}=fixture(t,{now:()=>now}),b=s.create(owner,body(),randomUUID());enter(s,entrant,b.id);const old=s.claim();now+=46000;const next=s.claim();assert.equal(next.id,old.id);assert.equal(next.seed,old.seed);assert.notEqual(next.lease,old.lease);assert.equal(s.finish(old,result(old,0)),false);assert.equal(s.finish(next,result(next,0)),true);assert.equal(s.me(entrant).balance,1087.5);});
test('three abandoned worker leases refund instead of holding credits forever',t=>{let now=1780000000000;const {s,owner,entrant}=fixture(t,{now:()=>now}),b=s.create(owner,body(),randomUUID()),a=enter(s,entrant,b.id);for(let i=0;i<3;i++){assert.ok(s.claim());now+=46000;}assert.equal(s.claim(),null);assert.equal(s.attempt(a.id).status,'refunded');assert.equal(s.me(entrant).balance,1000);});
test('balance, accepted builds and idempotency survive closing and reopening SQLite',t=>{const dir=mkdtempSync(join(tmpdir(),'wm-test-')),path=join(dir,'arena.sqlite');let s=new Store(path,{seed:false});t.after(()=>{s.close();for(const f of readdirSync(dir))unlinkSync(join(dir,f));rmdirSync(dir);});const owner=s.session({name:'Creator'}),entrant=s.session({name:'Entrant'}),b=s.create(owner.me.id,body(),randomUUID()),key=randomUUID(),a=enter(s,entrant.me.id,b.id,key);s.close();s=new Store(path,{seed:false});assert.equal(s.auth(entrant.token).account,entrant.me.id);assert.equal(s.me(entrant.me.id).balance,990);assert.equal(enter(s,entrant.me.id,b.id,key).id,a.id);const job=s.claim();s.finish(job,result(job,0));assert.equal(s.me(entrant.me.id).balance,1087.5);});
test('canonical input snapshots preserve customization and reject unknown fields',()=>{const m=clone(PRESETS[0]);m.front=3;m.modules.forEach(p=>p.r=3);m.modules[0].c='#aaccdd';m.number=66;m.accent='#feaa88';const p=packChallenge(m,'quarry',44);assert.equal(canonicalBlueprint(p).fr,3);assert.equal(canonicalBlueprint(p).m[0][6],'#aaccdd');assert.throws(()=>canonicalBlueprint({...p,result:{winner:0}}),/Unknown/);});

test('a refund from yesterday does not enlarge today’s entry allowance',t=>{let now=Date.UTC(2026,8,12,23,59,50);const {s,owner,entrant}=fixture(t,{now:()=>now}),b1=s.create(owner,body(),randomUUID()),b2=s.create(owner,body(),randomUUID());enter(s,entrant,b1.id);const old=s.claim();now+=20000;enter(s,entrant,b2.id);assert.equal(s.me(entrant).spentToday,10);s.finish(old,null,'Late failure');assert.equal(s.me(entrant).spentToday,10);});
test('old-engine idle contracts return reserves and queued jobs refund on upgrade',t=>{const {s,owner,entrant}=fixture(t),idle=s.create(owner,body(),randomUUID()),busy=s.create(owner,body(),randomUUID()),a=enter(s,entrant,busy.id);s.db.prepare('UPDATE bounties SET version=?').run(JSON.stringify({hash:'old-release'}));s.expire();assert.equal(s.bounty(idle.id).status,'archived');assert.equal(s.claim(),null);s.expire();assert.equal(s.attempt(a.id).status,'refunded');assert.equal(s.me(owner).balance,1000);assert.equal(s.me(entrant).balance,1000);});

async function request(app,path,{token,method='GET',body,key}={}){const res=await fetch(app.url+'/api'+path,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{}),...(key?{'Idempotency-Key':key}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:res.status,data:await res.json()};}
test('HTTP race accepts one challenger and rejects the other without charging',async t=>{const app=await startServer({port:0,database:':memory:',seed:false,workers:false});t.after(()=>app.close());const users=await Promise.all(['Owner','A','B'].map(name=>request(app,'/session',{method:'POST',body:{name}}))),[owner,a,b]=users.map(u=>u.data);const contract=(await request(app,'/bounties',{method:'POST',token:owner.token,body:body(),key:randomUUID()})).data;const r=await Promise.all([a,b].map(u=>request(app,'/bounties/'+contract.id+'/attempts',{method:'POST',token:u.token,body:{blueprint:blueprint(),maxEntry:10,maxPlatformFeeBps:250},key:randomUUID()})));assert.deepEqual(r.map(v=>v.status).sort(),[202,409]);assert.equal(app.store.me(a.me.id).balance+app.store.me(b.me.id).balance,1990);const tamper=await request(app,'/attempts/'+r.find(r=>r.status===202).data.id,{method:'POST',token:a.token,body:{winner:0}});assert.equal(tamper.status,404);});
test('real worker settles the same deterministic battle as the browser engine',async t=>{const app=await startServer({port:0,database:':memory:',seed:false});t.after(()=>app.close());const owner=(await request(app,'/session',{method:'POST',body:{name:'Owner'}})).data,entrant=(await request(app,'/session',{method:'POST',body:{name:'Engineer'}})).data,b=(await request(app,'/bounties',{method:'POST',token:owner.token,body:body(),key:randomUUID()})).data,a=(await request(app,'/bounties/'+b.id+'/attempts',{method:'POST',token:entrant.token,body:{blueprint:packChallenge(PRESETS[7],'foundry',0),maxEntry:10,maxPlatformFeeBps:250},key:randomUUID()})).data;let receipt;for(let i=0;i<100;i++){receipt=(await request(app,'/attempts/'+a.id,{token:entrant.token})).data;if(receipt.status==='settled')break;await new Promise(r=>setTimeout(r,40));}assert.equal(receipt.status,'settled');const expected=new Battle(PRESETS[7],PRESETS[0],'foundry',receipt.replay.seed,{swapSpawns:receipt.replay.swapSpawns}).run();assert.equal(receipt.result.winner,expected.winner);assert.deepEqual(receipt.result.integrity,expected.integrity);assert.equal(receipt.result.time,expected.time);});
test('HTTP serves only dist, rejects cross-origin writes and does not expose the database',async t=>{const app=await startServer({port:0,database:':memory:',seed:false,workers:false});t.after(()=>app.close());assert.equal((await fetch(app.url+'/')).status,200);assert.equal((await fetch(app.url+'/server/store.mjs')).status,404);assert.equal((await fetch(app.url+'/var/war-machines.sqlite')).status,404);const res=await fetch(app.url+'/api/session',{method:'POST',headers:{Origin:'https://attacker.invalid','Content-Type':'application/json'},body:'{}'});assert.equal(res.status,403);});

test('release identity is portable across LF and CRLF checkouts, but detects source edits',()=>{assert.equal(hashSimulationSources('a\nb\n','c\nd\n'),hashSimulationSources('a\r\nb\r\n','c\r\nd\r\n'));assert.notEqual(hashSimulationSources('a\nb','c\nd'),hashSimulationSources('a\nchanged','c\nd'));});
