import test from 'node:test';
import assert from 'node:assert/strict';
import {DEFAULT_RULES,PRESETS,clone,partSpec,integrityBreakdown,timeoutScore,packChallenge,unpackChallenge,HEAT_DANGER,HEAT_LIMIT,HEAT_RECOVERY} from '../dist/data.mjs';
import {Battle,DT,world} from '../dist/engine.mjs';
import {engineeringReport,weaponRows,battleAdvice,pickModule,combatSummary,stressTest} from '../dist/engineering.mjs';

test('engineering report explains missing mobility, power, heat, and reversed guns',()=>{const m=clone(PRESETS[0]);m.modules=m.modules.filter(p=>!['wheel','cooler','battery'].includes(p.id));m.front=2;const notes=engineeringReport(m,DEFAULT_RULES);assert.ok(notes.some(n=>n.level==='error'&&n.category==='Mobility'));assert.ok(notes.some(n=>n.text.includes('Energy reserve')));assert.ok(notes.some(n=>n.text.includes('overheat')));assert.ok(notes.some(n=>n.text.includes('away from')));});
test('engineering warnings account for the selected arena and stay read-only',()=>{const m=clone(PRESETS[0]),before=clone(m);const normal=engineeringReport(m,DEFAULT_RULES,'foundry'),hot=engineeringReport(m,DEFAULT_RULES,'furnace');assert.ok(normal.some(n=>n.text.includes('The Foundry')));assert.ok(hot.some(n=>n.text.includes('Furnace Nine')));assert.deepEqual(m,before);});
test('engineering report discloses fire-control saturation for a matching weapon bank',()=>{const m=clone(PRESETS[0]);m.modules.push({id:'cannon',x:2,y:2,r:0},{id:'cannon',x:2,y:1,r:0});const notes=engineeringReport(m,DEFAULT_RULES);assert.ok(notes.some(n=>n.category==='Weapons'&&n.text.includes('3 × Hammer cannon reload at 1.18×')));});
test('3D picking selects the closest visible layer and respects edit-level filters',()=>{const m={modules:[{id:'core',x:4,y:4,r:0},{id:'deck',x:4,y:4,z:1,r:0},{id:'laser',x:4,y:4,z:2,r:0}]},ray={origin:[0,10,0],direction:[0,-1,0]};assert.equal(pickModule(ray,m,{allLevels:true}).id,'laser');assert.equal(pickModule(ray,m,{layer:0}).id,'core');assert.equal(pickModule(ray,m,{layer:1,full:false,allLevels:true}).id,'deck');assert.equal(pickModule({origin:[5,10,0],direction:[0,-1,0]},m,{allLevels:true}),null);assert.equal(pickModule(null,m),null);});
test('weapon status inspection cannot alter combat or its deterministic result',()=>{const a=new Battle(PRESETS[9],PRESETS[8],'salt',901),b=new Battle(PRESETS[9],PRESETS[8],'salt',901);a.vehicles[0].focusUid=1200;b.vehicles[0].focusUid=1200;for(let i=0;i<900&&!a.result;i++){const before=clone(a.vehicles);for(const v of a.vehicles)for(const m of v.modules)if(partSpec(m).rate)a.weaponStatus(v,m);assert.deepEqual(a.vehicles,before);a.step();b.step();}assert.deepEqual(a.run(),b.run());assert.deepEqual(a.vehicles,b.vehicles);});
test('weapon damage attribution and floating damage labels are bounded',()=>{const b=new Battle(PRESETS[0],PRESETS[0]),v=b.vehicles[1],gun=b.vehicles[0].modules.find(m=>partSpec(m).rate),target=v.modules.find(m=>m.id==='core');v.shield=0;const before=target.hp;b.damageModule(v,target,27,0,{weaponUid:gun.uid});assert.equal(gun.dealt,27);assert.equal(target.hp,before-27);assert.equal(b.damageLabels.length,1);b.damageModule(v,target,10,0,{weaponUid:gun.uid});assert.equal(b.damageLabels.length,1);assert.equal(b.damageLabels[0].amount,37);for(let i=0;i<50;i++)b.step();assert.equal(b.damageLabels.length,0);});
test('battle report counts destroyed weapons and explains core loss without unrelated counters',()=>{const b=new Battle(PRESETS[0],PRESETS[0]);b.run();const losing=b.result.winner===0?1:0,report=battleAdvice(b,losing),rows=weaponRows(b.vehicles[losing]);assert.ok(report.rows.length);assert.ok(rows.every(r=>r.alive<=r.count&&r.damage>=0));if(b.vehicles[losing].dead)assert.ok(report.notes.some(n=>n.includes('core was destroyed')));assert.ok(!report.notes.some(n=>n.includes('Sentinel')));});
test('direct hit, projectile telemetry and report output agree',()=>{const b=new Battle(PRESETS[0],PRESETS[0]),enemy=b.vehicles[1],victim=enemy.modules.find(m=>m.id==='core'),gun=b.vehicles[0].modules.find(m=>m.id==='cannon'),p=world(enemy,victim);b.arena.obstacles=[];enemy.shield=0;b.projectiles=[{x:p.x-20,y:p.y,h:p.h+15,vx:1200,vy:0,vh:0,gravity:0,life:1,side:0,sourceUid:gun.uid,kind:'laser',damage:25,pierce:0,splash:0,hitIds:[]}];b.updateProjectiles(DT);assert.equal(gun.landed,1);assert.equal(gun.dealt,25);assert.equal(weaponRows(b.vehicles[0]).find(r=>r.id==='cannon').damage,25);});
test('timeout scoring weights live systems and combat summaries expose failure causes',()=>{const b=new Battle(PRESETS[0],PRESETS[1],'foundry',73),v=b.vehicles[0];const core=v.modules.find(m=>m.id==='core');core.hp=partSpec(core).hp;const breakdown=integrityBreakdown(v);assert.equal(breakdown.core,1);assert.ok(timeoutScore(v)>0);b.time=3;b.arena.obstacles=[];v.x=260;v.y=400;b.vehicles[1].x=1100;b.vehicles[1].y=700;for(let i=0;i<3;i++)b.step();const report=combatSummary(b);assert.ok(report.timeline.some(e=>e.kind==='status'));assert.ok(Object.hasOwn(report.failures,'range'));});
test('stress testing repeats fixed seeds and returns terrain and weapon aggregates',()=>{const result=stressTest(PRESETS[0],PRESETS[1],'foundry',19,{seeds:[19,20]});assert.equal(result.runs.length,2);assert.equal(result.terrainScores.length,1);assert.ok(Number.isFinite(result.summary.averageSurvival));assert.ok(Array.isArray(result.damagePerWeapon));});
test('autonomous machines steer around obstructions without a recovery jump',()=>{const b=new Battle(PRESETS[0],PRESETS[1],'foundry',19);let maxStep=0;while(!b.result){const before=b.vehicles.map(v=>({x:v.x,y:v.y}));b.step();for(let i=0;i<2;i++)maxStep=Math.max(maxStep,Math.hypot(b.vehicles[i].x-before[i].x,b.vehicles[i].y-before[i].y));}const moves=b.timeline.filter(e=>e.kind==='movement'&&e.text.includes('navigating around an obstruction'));assert.ok(moves.length>0);assert.ok(b.vehicles.some(v=>v.repositionCount>0));assert.ok(maxStep<3);});
test('sensor arrays reduce targeting range and aim quality as they are damaged',()=>{const machine=clone(PRESETS[0]);const cooler=machine.modules.find(m=>m.id==='cooler');cooler.id='sensor';const b=new Battle(machine,PRESETS[1],'foundry',44),v=b.vehicles[0],enemy=b.vehicles[1],gun=v.modules.find(m=>partSpec(m).rate),target=b.chooseTarget(v,enemy),sensor=v.modules.find(m=>m.id==='sensor');const intact=v.s.sensor,range=b.weaponWindow(v,gun,enemy,target).range;sensor.hp=partSpec(sensor).hp*.2;b.recalc(v);assert.ok(v.s.sensor<intact);assert.ok(b.weaponWindow(v,gun,enemy,target).range<range);});
test('damaged batteries can surge before destruction and expose a deterministic warning event',()=>{const b=new Battle(PRESETS[0],PRESETS[1],'foundry',45),v=b.vehicles[0],battery=v.modules.find(m=>m.id==='battery');battery.hp=partSpec(battery).hp*.3;v.heat=125;b.recalc(v);for(let i=0;i<20&&!v.batterySurges;i++)b.updateBatteryInstability(v,1);assert.ok(v.batterySurges>0);assert.ok(b.events.some(e=>e.text.includes('unstable surge')));assert.ok(battery.hp>0);});
test('escort objectives serialize and advance cargo to extraction',()=>{const packed=packChallenge(PRESETS[0],'foundry',77,DEFAULT_RULES,'escort');const decoded=unpackChallenge(packed);assert.equal(decoded.objective,'escort');const b=new Battle(PRESETS[0],PRESETS[1],'foundry',77,{objective:decoded.objective});b.vehicles[1].dead=true;b.vehicles[0].x=150;b.vehicles[0].y=400;for(let i=0;i<60;i++)b.updateEscort(DT);assert.ok(b.escort[0].progress>0);b.escort[0].x=1050;b.escort[0].progress=.999;b.vehicles[0].x=1050;b.updateEscort(DT);assert.equal(b.escort[0].reached,true);});
test('heat and power bands reduce a loaded machine before hard lockout',()=>{const b=new Battle(PRESETS[0],PRESETS[1],'foundry',188),v=b.vehicles[0],enemy=b.vehicles[1];b.arena.obstacles=[];b.time=3;b.tick=180;v.x=300;v.y=400;enemy.x=620;enemy.y=400;v.heat=HEAT_DANGER+3;v.energy=v.maxEnergy*.1;for(const m of v.modules)if(partSpec(m).rate)m.cd=0;b.updateVehicle(v,enemy,DT);assert.ok(v.heatWarnLevel>=2);assert.ok(v.powerWarnLevel>=1);assert.ok(v.peakHeat>=HEAT_DANGER);const gun=v.modules.find(m=>partSpec(m).rate);assert.ok(['COOLING DOWN','OVERHEAT RISK','OVERHEAT','HEAT LIMITED','POWER LIMITED','LOW POWER'].includes(b.weaponStatus(v,gun)));});
test('thermal retreat pauses fire and backs an autonomous machine away until safe',()=>{const b=new Battle(PRESETS[0],PRESETS[1],'foundry',190),v=b.vehicles[0],enemy=b.vehicles[1];b.arena.obstacles=[];b.time=3;b.tick=180;v.x=500;v.y=400;enemy.x=560;enemy.y=400;v.heat=HEAT_DANGER+2;v.energy=v.maxEnergy;for(const m of v.modules)if(partSpec(m).rate)m.cd=0;const before=v.x;b.updateVehicle(v,enemy,DT);assert.equal(v.coolingDown,true);assert.equal(v.shots,0);assert.ok(v.x<before);assert.ok(v.cooldownCount>=1);assert.ok(b.events.some(e=>e.text.includes('thermal retreat engaged')));v.heat=HEAT_RECOVERY-1;b.updateVehicle(v,enemy,DT);assert.equal(v.coolingDown,false);assert.ok(b.events.some(e=>e.text.includes('cooling complete')));});
test('hard overheat emits a clear lockout event and recovers below the reset band',()=>{const b=new Battle(PRESETS[0],PRESETS[1],'foundry',189),v=b.vehicles[0],enemy=b.vehicles[1];b.arena.obstacles=[];b.time=3;b.tick=180;v.x=300;v.y=400;enemy.x=620;enemy.y=400;v.heat=HEAT_LIMIT+3;v.energy=v.maxEnergy;for(const m of v.modules)if(partSpec(m).rate)m.cd=0;b.updateVehicle(v,enemy,DT);assert.equal(v.overheated,true);assert.ok(b.events.some(e=>e.text.includes('firing locked')));v.heat=20;b.updateVehicle(v,enemy,DT);assert.equal(v.overheated,false);assert.ok(b.events.some(e=>e.text.includes('back online')));});
test('core destruction cripples power but does not end the battle',()=>{const b=new Battle(PRESETS[0],PRESETS[1],'foundry',314),v=b.vehicles[1],core=v.modules.find(m=>m.id==='core'),power=v.s.power,cooling=v.s.cooling;b.damageModule(v,core,partSpec(core).hp+1,0,{bypass:true,cause:'test'});assert.equal(v.dead,false);assert.equal(v.coreLost,true);assert.equal(b.result,null);assert.ok(v.s.power<power);assert.ok(v.s.cooling<cooling);assert.ok(b.events.some(e=>e.kind==='core'&&e.text.includes('combat continues')));});

test('a high-heat weapon waits before crossing the hard lockout and coolant purging cools its visual state',()=>{const b=new Battle(PRESETS[0],PRESETS[1],'foundry',913,{mode:'command'}),v=b.vehicles[0],enemy=b.vehicles[1],gun=v.modules.find(m=>m.id==='cannon');b.time=3;b.tick=180;b.arena.obstacles=[];v.x=300;v.y=400;enemy.x=620;enemy.y=400;gun.id='plasma';gun.hp=partSpec(gun).hp;for(const m of v.modules)if(partSpec(m).rate)m.cd=m===gun?0:99;v.heat=84;v.energy=v.maxEnergy;b.weaponWindow=()=>({status:'READY',range:1000});b.updateVehicle(v,enemy,DT);assert.equal(v.shots,0);assert.ok(v.heat<HEAT_LIMIT);assert.ok(gun.heatWait>0);assert.equal(b.weaponStatus(v,gun),'HEAT SAFETY');gun.thermal=.8;v.heat=90;assert.equal(b.activate(0,'vent'),true);assert.ok(gun.thermal<.8);assert.ok(b.combatEvents.some(e=>e.kind==='thermal'&&e.phase==='purge'));});
