import test from 'node:test';
import assert from 'node:assert/strict';
import {DEFAULT_RULES,PRESETS,clone,partSpec,integrityBreakdown,timeoutScore,packChallenge,unpackChallenge} from '../dist/data.mjs';
import {Battle,DT,world} from '../dist/engine.mjs';
import {engineeringReport,weaponRows,battleAdvice,pickModule,combatSummary,stressTest} from '../dist/engineering.mjs';

test('engineering report explains missing mobility, power, heat, and reversed guns',()=>{const m=clone(PRESETS[0]);m.modules=m.modules.filter(p=>!['wheel','cooler','battery'].includes(p.id));m.front=2;const notes=engineeringReport(m,DEFAULT_RULES);assert.ok(notes.some(n=>n.level==='error'&&n.category==='Mobility'));assert.ok(notes.some(n=>n.text.includes('Energy reserve')));assert.ok(notes.some(n=>n.text.includes('overheat')));assert.ok(notes.some(n=>n.text.includes('away from')));});
test('engineering warnings account for the selected arena and stay read-only',()=>{const m=clone(PRESETS[0]),before=clone(m);const normal=engineeringReport(m,DEFAULT_RULES,'foundry'),hot=engineeringReport(m,DEFAULT_RULES,'furnace');assert.ok(normal.some(n=>n.text.includes('The Foundry')));assert.ok(hot.some(n=>n.text.includes('Furnace Nine')));assert.deepEqual(m,before);});
test('engineering report discloses fire-control saturation for a matching weapon bank',()=>{const m=clone(PRESETS[0]);m.modules.push({id:'cannon',x:2,y:2,r:0},{id:'cannon',x:2,y:1,r:0});const notes=engineeringReport(m,DEFAULT_RULES);assert.ok(notes.some(n=>n.category==='Weapons'&&n.text.includes('3 × Hammer cannon reload at 1.18×')));});
test('3D picking selects the closest visible layer and respects edit-level filters',()=>{const m={modules:[{id:'core',x:4,y:4,r:0},{id:'deck',x:4,y:4,z:1,r:0},{id:'laser',x:4,y:4,z:2,r:0}]},ray={origin:[0,10,0],direction:[0,-1,0]};assert.equal(pickModule(ray,m,{allLevels:true}).id,'laser');assert.equal(pickModule(ray,m,{layer:0}).id,'core');assert.equal(pickModule(ray,m,{layer:1,full:false,allLevels:true}).id,'deck');assert.equal(pickModule({origin:[5,10,0],direction:[0,-1,0]},m,{allLevels:true}),null);assert.equal(pickModule(null,m),null);});
test('weapon status inspection cannot alter combat or its deterministic result',()=>{const a=new Battle(PRESETS[9],PRESETS[8],'salt',901),b=new Battle(PRESETS[9],PRESETS[8],'salt',901);a.vehicles[0].focusUid=1200;b.vehicles[0].focusUid=1200;for(let i=0;i<900&&!a.result;i++){const before=clone(a.vehicles);for(const v of a.vehicles)for(const m of v.modules)if(partSpec(m).rate)a.weaponStatus(v,m);assert.deepEqual(a.vehicles,before);a.step();b.step();}assert.deepEqual(a.run(),b.run());assert.deepEqual(a.vehicles,b.vehicles);});
test('weapon damage attribution and floating damage labels are bounded',()=>{const b=new Battle(PRESETS[0],PRESETS[0]),v=b.vehicles[1],gun=b.vehicles[0].modules.find(m=>partSpec(m).rate),target=v.modules.find(m=>m.id==='core');v.shield=0;const before=target.hp;b.damageModule(v,target,27,0,{weaponUid:gun.uid});assert.equal(gun.dealt,27);assert.equal(target.hp,before-27);assert.equal(b.damageLabels.length,1);b.damageModule(v,target,10,0,{weaponUid:gun.uid});assert.equal(b.damageLabels.length,1);assert.equal(b.damageLabels[0].amount,37);for(let i=0;i<50;i++)b.step();assert.equal(b.damageLabels.length,0);});
test('battle report counts destroyed weapons and explains core loss without unrelated counters',()=>{const b=new Battle(PRESETS[0],PRESETS[0]);b.run();const losing=b.result.winner===0?1:0,report=battleAdvice(b,losing),rows=weaponRows(b.vehicles[losing]);assert.ok(report.rows.length);assert.ok(rows.every(r=>r.alive<=r.count&&r.damage>=0));if(b.vehicles[losing].dead)assert.ok(report.notes.some(n=>n.includes('core was destroyed')));assert.ok(!report.notes.some(n=>n.includes('Sentinel')));});
test('direct hit, projectile telemetry and report output agree',()=>{const b=new Battle(PRESETS[0],PRESETS[0]),enemy=b.vehicles[1],victim=enemy.modules.find(m=>m.id==='core'),gun=b.vehicles[0].modules.find(m=>m.id==='cannon'),p=world(enemy,victim);b.arena.obstacles=[];enemy.shield=0;b.projectiles=[{x:p.x-20,y:p.y,h:p.h+15,vx:1200,vy:0,vh:0,gravity:0,life:1,side:0,sourceUid:gun.uid,kind:'laser',damage:25,pierce:0,splash:0,hitIds:[]}];b.updateProjectiles(DT);assert.equal(gun.landed,1);assert.equal(gun.dealt,25);assert.equal(weaponRows(b.vehicles[0]).find(r=>r.id==='cannon').damage,25);});
test('timeout scoring weights live systems and combat summaries expose failure causes',()=>{const b=new Battle(PRESETS[0],PRESETS[1],'foundry',73),v=b.vehicles[0];const core=v.modules.find(m=>m.id==='core');core.hp=partSpec(core).hp;const breakdown=integrityBreakdown(v);assert.equal(breakdown.core,1);assert.ok(timeoutScore(v)>0);b.time=3;b.arena.obstacles=[];v.x=260;v.y=400;b.vehicles[1].x=1100;b.vehicles[1].y=700;for(let i=0;i<3;i++)b.step();const report=combatSummary(b);assert.ok(report.timeline.some(e=>e.kind==='status'));assert.ok(Object.hasOwn(report.failures,'range'));});
test('stress testing repeats fixed seeds and returns terrain and weapon aggregates',()=>{const result=stressTest(PRESETS[0],PRESETS[1],'foundry',19,{seeds:[19,20]});assert.equal(result.runs.length,2);assert.equal(result.terrainScores.length,1);assert.ok(Number.isFinite(result.summary.averageSurvival));assert.ok(Array.isArray(result.damagePerWeapon));});
test('sensor arrays reduce targeting range and aim quality as they are damaged',()=>{const machine=clone(PRESETS[0]);const cooler=machine.modules.find(m=>m.id==='cooler');cooler.id='sensor';const b=new Battle(machine,PRESETS[1],'foundry',44),v=b.vehicles[0],enemy=b.vehicles[1],gun=v.modules.find(m=>partSpec(m).rate),target=b.chooseTarget(v,enemy),sensor=v.modules.find(m=>m.id==='sensor');const intact=v.s.sensor,range=b.weaponWindow(v,gun,enemy,target).range;sensor.hp=partSpec(sensor).hp*.2;b.recalc(v);assert.ok(v.s.sensor<intact);assert.ok(b.weaponWindow(v,gun,enemy,target).range<range);});
test('damaged batteries can surge before destruction and expose a deterministic warning event',()=>{const b=new Battle(PRESETS[0],PRESETS[1],'foundry',45),v=b.vehicles[0],battery=v.modules.find(m=>m.id==='battery');battery.hp=partSpec(battery).hp*.3;v.heat=125;b.recalc(v);for(let i=0;i<20&&!v.batterySurges;i++)b.updateBatteryInstability(v,1);assert.ok(v.batterySurges>0);assert.ok(b.events.some(e=>e.text.includes('unstable surge')));assert.ok(battery.hp>0);});
test('escort objectives serialize and advance cargo to extraction',()=>{const packed=packChallenge(PRESETS[0],'foundry',77,DEFAULT_RULES,'escort');const decoded=unpackChallenge(packed);assert.equal(decoded.objective,'escort');const b=new Battle(PRESETS[0],PRESETS[1],'foundry',77,{objective:decoded.objective});b.vehicles[1].dead=true;b.vehicles[0].x=150;b.vehicles[0].y=400;for(let i=0;i<60;i++)b.updateEscort(DT);assert.ok(b.escort[0].progress>0);b.escort[0].x=1050;b.escort[0].progress=.999;b.vehicles[0].x=1050;b.updateEscort(DT);assert.equal(b.escort[0].reached,true);});
