import test from 'node:test';
import assert from 'node:assert/strict';
import {DEFAULT_RULES,PRESETS,clone,partSpec} from '../dist/data.mjs';
import {Battle,DT,world} from '../dist/engine.mjs';
import {engineeringReport,weaponRows,battleAdvice,pickModule} from '../dist/engineering.mjs';

test('engineering report explains missing mobility, power, heat, and reversed guns',()=>{const m=clone(PRESETS[0]);m.modules=m.modules.filter(p=>!['wheel','cooler','battery'].includes(p.id));m.front=2;const notes=engineeringReport(m,DEFAULT_RULES);assert.ok(notes.some(n=>n.level==='error'&&n.category==='Mobility'));assert.ok(notes.some(n=>n.text.includes('Energy reserve')));assert.ok(notes.some(n=>n.text.includes('overheat')));assert.ok(notes.some(n=>n.text.includes('away from')));});
test('engineering warnings account for the selected arena and stay read-only',()=>{const m=clone(PRESETS[0]),before=clone(m);const normal=engineeringReport(m,DEFAULT_RULES,'foundry'),hot=engineeringReport(m,DEFAULT_RULES,'furnace');assert.ok(normal.some(n=>n.text.includes('The Foundry')));assert.ok(hot.some(n=>n.text.includes('Furnace Nine')));assert.deepEqual(m,before);});
test('3D picking selects the closest visible layer and respects edit-level filters',()=>{const m={modules:[{id:'core',x:4,y:4,r:0},{id:'deck',x:4,y:4,z:1,r:0},{id:'laser',x:4,y:4,z:2,r:0}]},ray={origin:[0,10,0],direction:[0,-1,0]};assert.equal(pickModule(ray,m,{allLevels:true}).id,'laser');assert.equal(pickModule(ray,m,{layer:0}).id,'core');assert.equal(pickModule(ray,m,{layer:1,full:false,allLevels:true}).id,'deck');assert.equal(pickModule({origin:[5,10,0],direction:[0,-1,0]},m,{allLevels:true}),null);assert.equal(pickModule(null,m),null);});
test('weapon status inspection cannot alter combat or its deterministic result',()=>{const a=new Battle(PRESETS[9],PRESETS[8],'salt',901),b=new Battle(PRESETS[9],PRESETS[8],'salt',901);a.vehicles[0].focusUid=1200;b.vehicles[0].focusUid=1200;for(let i=0;i<900&&!a.result;i++){const before=clone(a.vehicles);for(const v of a.vehicles)for(const m of v.modules)if(partSpec(m).rate)a.weaponStatus(v,m);assert.deepEqual(a.vehicles,before);a.step();b.step();}assert.deepEqual(a.run(),b.run());assert.deepEqual(a.vehicles,b.vehicles);});
test('weapon damage attribution and floating damage labels are bounded',()=>{const b=new Battle(PRESETS[0],PRESETS[0]),v=b.vehicles[1],gun=b.vehicles[0].modules.find(m=>partSpec(m).rate),target=v.modules.find(m=>m.id==='core');v.shield=0;const before=target.hp;b.damageModule(v,target,27,0,{weaponUid:gun.uid});assert.equal(gun.dealt,27);assert.equal(target.hp,before-27);assert.equal(b.damageLabels.length,1);b.damageModule(v,target,10,0,{weaponUid:gun.uid});assert.equal(b.damageLabels.length,1);assert.equal(b.damageLabels[0].amount,37);for(let i=0;i<50;i++)b.step();assert.equal(b.damageLabels.length,0);});
test('battle report counts destroyed weapons and explains core loss without unrelated counters',()=>{const b=new Battle(PRESETS[0],PRESETS[0]);b.run();const losing=b.result.winner===0?1:0,report=battleAdvice(b,losing),rows=weaponRows(b.vehicles[losing]);assert.ok(report.rows.length);assert.ok(rows.every(r=>r.alive<=r.count&&r.damage>=0));if(b.vehicles[losing].dead)assert.ok(report.notes.some(n=>n.includes('core was destroyed')));assert.ok(!report.notes.some(n=>n.includes('Sentinel')));});
test('direct hit, projectile telemetry and report output agree',()=>{const b=new Battle(PRESETS[0],PRESETS[0]),enemy=b.vehicles[1],victim=enemy.modules.find(m=>m.id==='core'),gun=b.vehicles[0].modules.find(m=>m.id==='cannon'),p=world(enemy,victim);b.arena.obstacles=[];enemy.shield=0;b.projectiles=[{x:p.x-20,y:p.y,h:p.h+15,vx:1200,vy:0,vh:0,gravity:0,life:1,side:0,sourceUid:gun.uid,kind:'laser',damage:25,pierce:0,splash:0,hitIds:[]}];b.updateProjectiles(DT);assert.equal(gun.landed,1);assert.equal(gun.dealt,25);assert.equal(weaponRows(b.vehicles[0]).find(r=>r.id==='cannon').damage,25);});
