import test from 'node:test';
import assert from 'node:assert/strict';
import {DEFAULT_RULES,PARTS,BY_ID,PRESETS,ARENAS,clone,stats,validate,connected,packChallenge,unpackChallenge,encodeChallenge,decodeChallenge} from '../dist/data.mjs';
import {Battle,DT,segmentBox} from '../dist/engine.mjs';
import {Geometry,VERTEX_STRIDE,workshopScene,battleScene} from '../dist/renderer.mjs';

test('all factory machines deploy within the shared budget',()=>{for(const m of PRESETS){assert.deepEqual(validate(m),[]);assert.ok(stats(m).cost<=1200);assert.equal(connected(m.modules).size,m.modules.length);}});
test('challenge roundtrip preserves Unicode, direction, doctrine and exact seed',()=>{const m=clone(PRESETS[0]);m.name='Météore 🔥';m.modules[0].r=3;m.stance='guarded';m.target='power';const p=packChallenge(m,'furnace',4294967295);const url='https://example.test/#challenge='+encodeChallenge(p);assert.deepEqual(decodeChallenge(url),{machine:m,arena:'furnace',seed:4294967295,limit:1200,rules:DEFAULT_RULES});});
test('rejects malformed, oversized, invalid-budget and overlapping challenges',()=>{const p=packChallenge(PRESETS[0],'foundry',12);for(const change of [o=>o.v=99,o=>o.b=5000,o=>o.m.push(o.m[0]),o=>o.m[0][1]=99,o=>o.m[0][0]=99,o=>o.d=Infinity,o=>o.t='execute',o=>o.e=-1]){const q=clone(p);change(q);assert.throws(()=>unpackChallenge(q));}assert.throws(()=>decodeChallenge('a'.repeat(64001)));assert.throws(()=>decodeChallenge('<script>'));});
test('incomplete local drafts persist but cannot enter a friend challenge',()=>{const m=clone(PRESETS[0]);m.modules=m.modules.filter(p=>p.id==='core');const o=packChallenge(m,'foundry',12);assert.deepEqual(unpackChallenge(o,true).machine,m);assert.throws(()=>unpackChallenge(o));});
test('identical seeds produce identical complete matches and event streams',()=>{const a=new Battle(PRESETS[0],PRESETS[5],'foundry',93542),b=new Battle(PRESETS[0],PRESETS[5],'foundry',93542);assert.deepEqual(a.run(),b.run());assert.deepEqual(a.events,b.events);assert.deepEqual(a.vehicles,b.vehicles);});
test('playback batching does not change a fixed-step simulation',()=>{const a=new Battle(PRESETS[2],PRESETS[7],'salt',518),b=new Battle(PRESETS[2],PRESETS[7],'salt',518);a.run();while(!b.result)for(let i=0;i<8&&!b.result;i++)b.step(DT);assert.deepEqual(a.result,b.result);});
test('destroying a sole connector detaches its entire branch',()=>{const m={...clone(PRESETS[0]),modules:[{id:'core',x:4,y:4,r:0},{id:'frame',x:5,y:4,r:0},{id:'cannon',x:6,y:4,r:0},{id:'wheel',x:4,y:5,r:0}]};const b=new Battle(m,PRESETS[0]);const v=b.vehicles[0],link=v.modules.find(m=>m.id==='frame');b.damageModule(v,link,1000,1);b.detach(v);assert.equal(v.modules.find(m=>m.id==='cannon').hp,0);assert.equal(v.detached,1);assert.ok(v.modules.find(m=>m.id==='wheel').hp>0);});
test('battery explosions damage adjacent parts without infinite recursion',()=>{const m={...clone(PRESETS[0]),modules:[{id:'core',x:4,y:4,r:0},{id:'battery',x:4,y:5,r:0},{id:'battery',x:5,y:5,r:0},{id:'wheel',x:3,y:4,r:0}]};const b=new Battle(m,PRESETS[0]);b.damageModule(b.vehicles[0],b.vehicles[0].modules[1],1000,1);assert.ok(b.vehicles[0].modules[0].hp<300);assert.ok(b.vehicles[0].modules[2].hp<85);assert.ok(b.events.some(e=>e.text.includes('chain reaction')));});
test('armor mitigates direct damage and shields absorb it first',()=>{const b=new Battle(PRESETS[5],PRESETS[0]),v=b.vehicles[0],armor=v.modules.find(m=>m.id==='armor');const before=armor.hp;b.damageModule(v,armor,100,1);assert.equal(armor.hp,before);assert.equal(v.shield,78);v.shield=0;b.damageModule(v,armor,100,1);assert.equal(armor.hp,before-62);});
test('lost mobility reduces speed; excess mass has a measurable cost',()=>{const a=stats(PRESETS[0]),heavy=clone(PRESETS[0]);heavy.modules.push({id:'armor',x:1,y:1,r:0});assert.ok(stats(heavy).speed<a.speed);assert.equal(stats({modules:heavy.modules.filter(m=>!BY_ID[m.id].thrust)}).speed,0);});
test('collision rays handle grazing, parallel and obstruction cases',()=>{const b={x:10,y:10,w:10,h:10};assert.equal(segmentBox(0,15,40,15,b),.25);assert.equal(segmentBox(0,0,40,0,b),null);assert.equal(segmentBox(15,0,15,40,b),.25);assert.equal(segmentBox(15,15,15,15,b),0);});
test('every opponent completes in every arena with bounded finite state',()=>{for(const arena of ARENAS)for(let i=0;i<PRESETS.length;i++){const b=new Battle(PRESETS[0],PRESETS[i],arena.id,100+i);const r=b.run();assert.ok(r.time<=100+DT);assert.ok([-1,0,1].includes(r.winner));for(const v of b.vehicles){for(const key of ['x','y','heat','energy','shield'])assert.ok(Number.isFinite(v[key]),`${arena.id} ${i} ${key}`);assert.ok(v.energy>=-1e-6);assert.ok(v.shield>=0);assert.ok(v.modules.every(m=>m.hp>=0));}}});
test('all component meshes produce finite, aligned vertex data',()=>{for(const p of PARTS){const g=new Geometry();g.module({id:p.id},'#e5a849');assert.ok(g.vertices.length>0);assert.equal(g.vertices.length%(VERTEX_STRIDE*3),0);assert.ok(g.vertices.every(Number.isFinite));}const g=workshopScene(PRESETS[0]);assert.ok(g.vertices.every(Number.isFinite));const b=new Battle(PRESETS[0],PRESETS[1]);b.vehicles.forEach(v=>b.recalc(v));assert.ok(battleScene(b).vertices.every(Number.isFinite));});
