import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, sep } from 'node:path';
import { pathToFileURL } from 'node:url';
import { assertSimulationSourceGraph, hashSimulationSources } from '../server/simulation-hash.mjs';
import { verifyRelease } from '../scripts/verify-release.mjs';
import { AMBIGUOUS_ENGINE_HASH, C804_ENGINE_HASH, E62_ENGINE_HASH, ENGINE_EVALUATORS, ESCROW, LEGACY_ENGINE_HASH, evaluate } from '../settlement/protocol.mjs';
import { Battle as CurrentBattle } from '../dist/engine.mjs';
import { packChallenge as pack4, PRESETS as presets4 } from '../settlement/engines/data.mjs';
import { packChallenge as packE62, PRESETS as presetsE62 } from '../settlement/engines/e62d2be3ff92293eb4ebb0a2357a039833ebf3a782ddff2d71dee367de1c5cf1/data.mjs';
import { packChallenge as packC804, PRESETS as presetsC804 } from '../settlement/engines/c804997d4145a830c246f10c358522c36ad9d820a86b313f74b5ced8a37340c6/data.mjs';

const root = new URL('../', import.meta.url);
const source = path => readFileSync(new URL(path, root), 'utf8');
const lf = value => value.replace(/\r\n/g, '\n');
const pairHash = (engine, data) => createHash('sha256').update(lf(engine)).update(lf(data)).digest('hex');

test('LF and CRLF preserve the legacy content identity; meaningful edits do not', () => {
  const engine = source('dist/engine.mjs'), data = source('dist/data.mjs');
  const crlf = value => lf(value).replace(/\n/g, '\r\n');
  assert.equal(hashSimulationSources(engine, data), hashSimulationSources(crlf(engine), crlf(data)));
  assert.notEqual(hashSimulationSources(engine, data), hashSimulationSources(engine + '\n// changed physics\n', data));
  assertSimulationSourceGraph(engine, data);
  assert.throws(() => assertSimulationSourceGraph(engine + "\nimport { x } from './new-physics.mjs';", data), /Unsupported engine simulation dependency/);
  assert.throws(() => assertSimulationSourceGraph(engine, data + "\nimport './new-catalog.mjs';"), /Unsupported data simulation dependency/);
});

test('verification reads only and rejects a stale or malformed stamp', () => {
  const directory = mkdtempSync(join(tmpdir(), 'war-release-'));
  try {
    const dist = join(directory, 'dist');
    mkdirSync(dist);
    const files = [join(dist, 'engine.mjs'), join(dist, 'data.mjs'), join(dist, 'release.mjs')];
    const engine = "import {PARTS} from './data.mjs';\nexport const value=PARTS.length;\n";
    const data = 'export const PARTS=[1];\n';
    const hash = pairHash(engine, data);
    writeFileSync(files[0], engine);
    writeFileSync(files[1], data);
    writeFileSync(files[2], `// Generated by scripts/stamp-release.mjs. Detects stale browser physics.\nexport const CLIENT_ENGINE_HASH='${hash}';\n`);
    const url = pathToFileURL(directory + sep);
    const before = files.map(file => [readFileSync(file), statSync(file).mtimeMs]);
    assert.equal(verifyRelease(url), hash);
    files.forEach((file, index) => { assert.deepEqual(readFileSync(file), before[index][0]); assert.equal(statSync(file).mtimeMs, before[index][1]); });
    writeFileSync(files[0], engine + '// meaningful edit\n');
    assert.throws(() => verifyRelease(url), /Stale simulation release stamp/);
    assert.equal(readFileSync(files[0], 'utf8'), engine + '// meaningful edit\n');
    writeFileSync(files[2], 'export const CLIENT_ENGINE_HASH="invalid";\n');
    assert.throws(() => verifyRelease(url), /Malformed simulation release stamp/);
  } finally { rmSync(directory, {recursive:true, force:true}); }
});

test('historical snapshots retain their exact engine and catalog pairs', () => {
  for (const hash of [C804_ENGINE_HASH, E62_ENGINE_HASH, AMBIGUOUS_ENGINE_HASH, 'f2779776cd3a4bf33d688b8384816c527c426654ef640f256353e0dbe37a0d45']) {
    const base = `settlement/engines/${hash}/`;
    assert.equal(pairHash(source(base + 'engine.mjs'), source(base + 'data.mjs')), hash);
    assert.match(source(base + 'engine.mjs'), /from ['"]\.\/data\.mjs['"]/);
  }
  assert.equal(pairHash(source(`settlement/engines/${LEGACY_ENGINE_HASH}.mjs`), source('settlement/engines/data.mjs')), LEGACY_ENGINE_HASH);
});

const fixture = (hash, pack, presets) => ({
  version:1, engineHash:hash, chainId:4217, escrow:ESCROW,
  bountyId:'7', attemptNonce:'1', reward:'1000001', entry:'10000', feeBps:250,
  defender:pack(presets[1], 'foundry', 0), challenger:pack(presets[0], 'foundry', 0),
  seed:1, reason:'battle', deadline:1700000600, buildDeadline:1700000300000,
  committedAt:1700000000000,
});

test('known historical evaluators keep their established fixed-seed result', () => {
  const established = {winner:1, reason:'Combat systems disabled', time:35.399999999999274, integrity:[0.06888797702092737,0.8168880781603366], damage:[508,1339]};
  const c804 = {winner:1, reason:'Combat systems disabled', time:22.266666666666683, integrity:[0.019647776183973176,0.9098774697568202], damage:[201,1541]};
  for (const [hash, pack, presets, expected] of [[LEGACY_ENGINE_HASH, pack4, presets4, established], [E62_ENGINE_HASH, packE62, presetsE62, established], [C804_ENGINE_HASH, packC804, presetsC804, c804]]) {
    assert.ok(ENGINE_EVALUATORS[hash]);
    assert.notEqual(ENGINE_EVALUATORS[hash].Battle, CurrentBattle);
    const result = evaluate(fixture(hash, pack, presets), 1700000000000).result;
    assert.deepEqual({winner:result.winner, reason:result.reason, time:result.time, integrity:result.integrity, damage:result.damage}, expected);
  }
});

test('ambiguous advertised history never silently selects current rules', () => {
  assert.equal(ENGINE_EVALUATORS[AMBIGUOUS_ENGINE_HASH], undefined);
  assert.throws(() => evaluate(fixture(AMBIGUOUS_ENGINE_HASH, packE62, presetsE62), 1700000000000), {code:'ENGINE_MISMATCH'});
});
