import test from 'node:test';
import assert from 'node:assert/strict';
import {ARENAS,PRESETS,clone,partSpec,terrainAt,stats,DEFAULT_RULES,validate} from '../dist/data.mjs';
import {Battle,DT,world} from '../dist/engine.mjs';
const machine=(gun='cannon')=>({...clone(PRESETS[0]),name:'Fixture',tactic:'balanced',range:180,modules:[{id:'core',x:4,y:4,r:0},{id:gun,x:4,y:3,r:0},{id:'wheel',x:3,y:4,r:0},{id:'wheel',x:5,y:4,r:0},{id:'battery',x:4,y:5,r:0}]});
function setup(){const b=new Battle(machine(),machine(),'salt',50,{mode:'command'});b.arena.terrain=[];b.arena.obstacles=[];b.time=3;b.tick=180;for(const v of b.vehicles){v.y=400;v.shield=0;v.holdFire=true;v.heat=70;}return b;}

test('coolant improves actual cooling while reducing wheeled movement',()=>{const dry=setup(),wet=setup();wet.arena.terrain=[{type:'coolant',x:0,y:0,w:1200,h:800}];for(let i=0;i<90;i++){dry.updateVehicle(dry.vehicles[0],dry.vehicles[1],DT);wet.updateVehicle(wet.vehicles[0],wet.vehicles[1],DT);}assert.ok(wet.vehicles[0].heat<dry.vehicles[0].heat-5);assert.ok(wet.vehicles[0].x<dry.vehicles[0].x-2);assert.equal(wet.vehicles[0].terrain,'coolant');});
test('treads lose less speed to rubble than wheels on the same route',()=>{const distance=(tracks,rough)=>{const b=setup(),v=b.vehicles[0];if(tracks)for(const m of v.modules)if(m.id==='wheel'){m.id='track';m.hp=partSpec(m).hp;}if(rough)b.arena.terrain=[{type:'rubble',x:0,y:0,w:1200,h:800}];const x=v.x;for(let i=0;i<180;i++)b.updateVehicle(v,b.vehicles[1],DT);return v.x-x;};const wheels=distance(false,true)/distance(false,false),tracks=distance(true,true)/distance(true,false);assert.ok(tracks>wheels+.1);});
test('terrain uses the core location consistently at patch boundaries',()=>{const a={terrain:[{type:'coolant',x:100,y:100,w:100,h:100}]};assert.equal(terrainAt(a,99.99,150).type,'road');assert.equal(terrainAt(a,100,150).type,'coolant');assert.equal(terrainAt(a,200,150).type,'coolant');assert.equal(terrainAt(a,200.01,150).type,'road');});
test('low beam is blocked mid-segment by a ridge; an elevated beam clears it',()=>{const fire=h=>{const b=setup(),v=b.vehicles[1];v.modules=v.modules.filter(m=>m.id==='core');v.x=690;b.recalc(v);const core=v.modules[0],hp=core.hp;b.arena.terrain=[{type:'ridge',x:550,y:300,w:80,h:200,height:25}];b.projectiles=[{x:500,y:400,h,vx:2400,vy:0,vh:0,gravity:0,beam:true,range:300,speed:2400,life:1,side:0,kind:'laser',damage:30,pierce:0,splash:0,hitIds:[]}];b.updateProjectiles(DT);return {damage:hp-core.hp,effect:b.effects.find(e=>e.type==='beam')};};const low=fire(12);assert.equal(low.damage,0);assert.ok(low.effect.tx<630);const high=fire(30);assert.equal(high.damage,30);assert.ok(high.effect.tx>650);});
test('ram must face and touch its target; a backwards wedge cannot damage from afar',()=>{const impact=rotation=>{const b=new Battle(machine('ram'),machine(),'salt',55),[a,z]=b.vehicles;a.x=500;a.y=z.y=400;z.x=545;a.modules.find(m=>m.id==='ram').r=rotation;a.a=Math.PI/2;z.a=-Math.PI/2;a.vx=90;z.vx=-50;a.shield=z.shield=0;const hp=z.modules.reduce((n,m)=>n+m.hp,0);b.collideVehicles();return hp-z.modules.reduce((n,m)=>n+m.hp,0);};assert.ok(impact(0)>0);assert.equal(impact(2),0);});
test('extra cosmetic randomness never changes the battle result',()=>{const a=new Battle(PRESETS[7],PRESETS[0],'quarry',456),b=new Battle(PRESETS[7],PRESETS[0],'quarry',456);for(let i=0;i<10000;i++)a.fxRandom();assert.deepEqual(a.run(),b.run());assert.deepEqual(a.events,b.events);});
test('rocket guidance follows the intended target height without dropping into flat ground early',()=>{const b=setup(),enemy=b.vehicles[1];enemy.x=900;const core=enemy.modules.find(m=>m.id==='core');b.projectiles=[{x:500,y:400,h:95,a:0,vx:330,vy:0,vh:-160,gravity:0,speed:330,range:530,life:2,side:0,targetUid:core.uid,kind:'rocket',damage:48,pierce:0,splash:0,hitIds:[]}];for(let i=0;i<45;i++)b.updateProjectiles(DT);assert.equal(b.projectiles.length,1);assert.ok(b.projectiles[0].h>15);assert.ok(Number.isFinite(b.projectiles[0].vh));});
test('official spawn swaps preserve participant identity and deterministic outcomes',()=>{const a=new Battle(PRESETS[0],PRESETS[7],'reservoir',923,{swapSpawns:true}),b=new Battle(PRESETS[0],PRESETS[7],'reservoir',923,{swapSpawns:true});assert.ok(a.vehicles[0].x>a.vehicles[1].x);assert.equal(a.vehicles[0].name,PRESETS[0].name);assert.equal(a.vehicles[0].side,0);assert.ok(a.vehicles[0].modules.every(m=>m.uid<1000));assert.ok(Math.cos(a.vehicles[0].a-Math.PI/2)<-.99);assert.deepEqual(a.run(),b.run());});
test('both new arenas have finite geometry data and legal terrain bounds',()=>{for(const id of ['reservoir','quarry']){const a=ARENAS.find(a=>a.id===id);assert.ok(a);for(const p of a.terrain){assert.ok(p.x>=0&&p.y>=0&&p.x+p.w<=1200&&p.y+p.h<=800);const t=terrainAt(a,p.x+p.w/2,p.y+p.h/2,9);assert.ok(Object.values(t).filter(v=>typeof v==='number').every(Number.isFinite));}}});
