import { runAutomaticSettlement } from './mainnet.mjs';
import {ARENAS,DEFAULT_RULES,MAX_MODULES,PARTS,PRESETS,clone,environmentProfile,normalizeRules,packChallenge,stats,terrainAt,unpackChallenge,validate} from '../../dist/data.mjs';
import {Battle} from '../../dist/engine.mjs';
import {engineeringReport} from '../../dist/engineering.mjs';
import {CLIENT_ENGINE_HASH} from '../../dist/release.mjs';
import {CREDIT_SCALE,PLATFORM_FEE_BPS,PLATFORM_FEE_POLICY,rewardQuote} from '../../dist/economy.mjs';
import {PART_GUIDANCE} from '../../dist/part-guidance.mjs';
import {serveStaticAsset} from './static-assets.mjs';
import {mainnetFetch} from './mainnet.mjs';

const json=value=>JSON.stringify(value),now=()=>Date.now(),id=()=>crypto.randomUUID();
const money=value=>Math.round(Number(value)*CREDIT_SCALE),credits=value=>Number(value)/CREDIT_SCALE;
const fail=(status,message)=>{const error=Error(message);error.status=status;throw error;};
const check=(value,message,status=400)=>{if(!value)fail(status,message);return value;};
const own=(value,key)=>Object.prototype.hasOwnProperty.call(value,key);
const fields=(value,allowed)=>{check(value&&typeof value==='object'&&!Array.isArray(value),'Expected a JSON object.');check(Object.keys(value).every(key=>allowed.includes(key)),'Unknown field in request.');};
const integer=(value,min,max,label)=>check(Number.isSafeInteger(value)&&value>=min&&value<=max,`${label} must be a whole number from ${min} to ${max}.`);
const text=(value,max,label)=>{check(typeof value==='string'&&value.trim().length>0&&value.trim().length<=max&&!/[\u0000-\u001f]/.test(value),`Invalid ${label}.`);return value.trim();};
const optionalParticipantName=value=>value===undefined||value===null||value===''?null:text(value,28,'pilot or machine name');
const participantIdentity=body=>{const name=optionalParticipantName(body.participantName);check(body.showAddress===undefined||typeof body.showAddress==='boolean','Choose whether to show your wallet address.');return {participantName:name,showAddress:body.showAddress===true};};
const participantMachineName=blueprint=>{try{return blueprint?unpackChallenge(parse(blueprint),true).machine.name:null;}catch{return null;}};
const parse=value=>{try{return JSON.parse(value);}catch{fail(500,'Stored game data is invalid.');}};
const validKey=value=>check(typeof value==='string'&&/^[A-Za-z0-9_-]{16,100}$/.test(value),'Supply a unique Idempotency-Key (16–100 letters, numbers, _ or -).');
const hex=async value=>{const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(byte=>byte.toString(16).padStart(2,'0')).join('');};
const secret=()=>{const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');};

function canonicalBlueprint(input,locked){
 fields(input,['v','n','p','t','g','d','s','a','e','b','q','fr','ac','gl','pt','no','f','m']);
 if(input.q)fields(input.q,['mode','combat','credits','parts','mass','weapons']);
 try{const packed=locked?{...input,a:locked.a,e:0,q:locked.q,b:locked.b}:input;const challenge=unpackChallenge(packed);return packChallenge(challenge.machine,challenge.arena,0,challenge.rules);}catch(error){fail(400,error.message||'Invalid blueprint.');}
}

function catalog(){return {mode:'demo',apiVersion:'3.0-sites-d1',discovery:'/.well-known/war-machines.json',openapi:'/api/openapi.json',terrainInfo:Object.fromEntries(ARENAS.flatMap(arena=>arena.terrain).map(terrain=>[terrain.type,terrain])),economics:{platformFee:PLATFORM_FEE_POLICY,creditScale:CREDIT_SCALE,amountUnit:'demo credits',network:null,maxInteger:1000000000,entryMin:0,rewardMin:0,rewardMustExceedEntry:false,personalCapsDefault:null,hours:{min:0,max:8760,zero:'No expiry'}},guest:['build','save local blueprints','share machines','browse','validate','practice'],loginRequired:['create bounty','enter official trial','save bounty','save account builds','account history'],walletAuth:'disabled',mpp:'disabled',versions:{hash:CLIENT_ENGINE_HASH},startingCredits:1000,parts:PARTS.map(part=>({...part,...PART_GUIDANCE[part.id]})),arenas:ARENAS,defaultRules:DEFAULT_RULES,examples:PRESETS.map(machine=>packChallenge(machine,'foundry',0)),rules:{oneActiveAttempt:true,combat:'auto',timeLimitSeconds:100,drawIntegrityThreshold:.025,entryRefund:'Technical failure only',spending:'Entry cap and daily account budget',payments:'Local sandbox only — no wallets, MPP, Tempo or cash value'}};}

async function dbAuth(db,request){
 const raw=request.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!raw)return null;
 const token=await hex(raw);let row=await db.prepare("SELECT id, name, 'owner' AS role FROM accounts WHERE token_hash=?").bind(token).first();
 if(row)return {...row,account:row.id};
 row=await db.prepare("SELECT id, account, name, 'agent' AS role FROM agent_keys WHERE token_hash=? AND revoked=0").bind(token).first();
 return row?{...row}:null;
}
function requireAuth(auth){return check(auth,'Sign in for bounty actions. Building and practice are open to guests.',401);}
function requireOwner(auth){check(auth?.role==='owner','This action requires the browser owner key.',403);return auth;}
async function account(db,accountId){
 const row=await db.prepare('SELECT id,name,balance,entry_cap,daily_cap FROM accounts WHERE id=?').bind(accountId).first();check(row,'Account not found.',404);
 const reserved=await db.prepare("SELECT COALESCE(SUM(reward),0) AS total FROM bounties WHERE owner=? AND status IN ('open','busy')").bind(accountId).first();
 const day=new Date(now()).setUTCHours(0,0,0,0),spent=await db.prepare("SELECT COALESCE(SUM(b.entry),0) AS total FROM attempts a JOIN bounties b ON b.id=a.bounty WHERE a.account=? AND a.created>=? AND a.status!='refunded'").bind(accountId,day).first();
 return {id:row.id,name:row.name,balance:credits(row.balance),entryCap:row.entry_cap===null?null:credits(row.entry_cap),dailyCap:row.daily_cap===null?null:credits(row.daily_cap),spentToday:credits(spent.total),reserved:credits(reserved.total),mode:'demo',identities:[],versions:{hash:CLIENT_ENGINE_HASH}};
}
async function ledger(db,accountId){const rows=await db.prepare('SELECT amount,kind,ref,created FROM ledger WHERE account=? ORDER BY created DESC LIMIT 100').bind(accountId).all();return rows.results.map(row=>({...row,amount:credits(row.amount)}));}
async function credit(db,accountId,delta,kind,ref){
 const existing=await db.prepare('SELECT amount FROM ledger WHERE account=? AND kind=? AND ref=?').bind(accountId,kind,ref).first();if(existing){check(existing.amount===delta,'Ledger conflict.',500);return;}
 const update=await db.prepare('UPDATE accounts SET balance=balance+? WHERE id=? AND balance+?>=0').bind(delta,accountId,delta).run();check(update.meta.changes===1,'Not enough sandbox credits.',409);
 await db.prepare('INSERT INTO ledger (id,account,amount,kind,ref,created) VALUES (?,?,?,?,?,?)').bind(id(),accountId,delta,kind,ref,now()).run();
}
async function bountyRow(db,bountyId){const row=await db.prepare('SELECT * FROM bounties WHERE id=?').bind(bountyId).first();return check(row,'Bounty not found.',404);}
async function bountyView(db,row,history=false){
 const owner=await db.prepare('SELECT name FROM accounts WHERE id=?').bind(row.owner).first(),quote=rewardQuote(credits(row.reward),credits(row.entry));
 const count=await db.prepare('SELECT COUNT(*) AS total FROM attempts WHERE bounty=?').bind(row.id).first();
 const value={id:row.id,owner:row.owner,ownerName:owner?.name||'Unknown engineer',title:row.title,blueprint:parse(row.blueprint),entry:credits(row.entry),reward:credits(row.reward),...quote,status:row.status,listed:!!row.listed,created:row.created,expires:row.expires||null,links:{share:'/#bounty='+row.id,self:'/api/bounties/'+row.id,attempts:'/api/bounties/'+row.id+'/attempts'},versions:{hash:CLIENT_ENGINE_HASH},compatible:true,activeAttempt:row.active_attempt,attempts:count.total,funded:['open','busy'].includes(row.status)};
 if(history){const rows=await db.prepare('SELECT id,result,blueprint,participant_name,show_address,created,updated FROM attempts WHERE bounty=? AND status IN (\'settled\',\'refunded\') ORDER BY created DESC LIMIT 20').bind(row.id).all();value.history=rows.results.map(attempt=>{let machineName=null;try{machineName=attempt.blueprint?unpackChallenge(parse(attempt.blueprint),true).machine.name:null;}catch{}return {id:attempt.id,participantName:attempt.participant_name||null,machineName,addressVisible:attempt.show_address===1,participantAddress:null,result:attempt.result?parse(attempt.result):null,created:attempt.created,updated:attempt.updated};});}
 return value;
}
async function expire(db){
 const rows=await db.prepare("SELECT * FROM bounties WHERE status='open' AND expires IS NOT NULL AND expires<=?").bind(now()).all();
 for(const row of rows.results){await credit(db,row.owner,row.reward,'release',row.id);await db.prepare("UPDATE bounties SET status='expired',updated=? WHERE id=? AND status='open'").bind(now(),row.id).run();}
}
async function prior(db,accountId,key,kind,body){validKey(key);const digest=await hex(json(body)),row=await db.prepare('SELECT kind,digest,ref FROM idempotency WHERE account=? AND key=?').bind(accountId,key).first();if(row){check(row.kind===kind&&row.digest===digest,'That idempotency key was used for a different request.',409);return row.ref;}return null;}
async function remember(db,accountId,key,kind,body,ref){await db.prepare('INSERT INTO idempotency (account,key,kind,digest,ref,created) VALUES (?,?,?,?,?,?)').bind(accountId,key,kind,await hex(json(body)),ref,now()).run();}

async function createBounty(db,auth,body,key){
 requireAuth(auth);fields(body,['title','blueprint','entry','reward','hours','listed','maxPlatformFeeBps']);const old=await prior(db,auth.account,key,'create',body);if(old)return bountyView(db,await bountyRow(db,old),true);
 check(auth.role==='owner','Agent keys cannot fund bounties on the hosted demo.',403);check(body.maxPlatformFeeBps===PLATFORM_FEE_BPS,'Acknowledge the 2.5% winning-reward platform fee with maxPlatformFeeBps: 250.',409);integer(body.entry,0,1000000000,'Entry');integer(body.reward,0,1000000000,'Reward');integer(body.hours,0,8760,'Duration');const listed=body.listed!==false;
 const blueprint=canonicalBlueprint(body.blueprint),title=text(body.title,70,'bounty title'),count=await db.prepare("SELECT COUNT(*) AS total FROM bounties WHERE owner=? AND status IN ('open','busy')").bind(auth.account).first();check(count.total<20,'Close an existing bounty first.',409);
 const bounty=id(),created=now(),reward=money(body.reward),debited=await db.prepare('UPDATE accounts SET balance=balance-? WHERE id=? AND balance>=?').bind(reward,auth.account,reward).run();check(debited.meta.changes===1,'Not enough available demo credits to fund this reward.',409);
 try{await db.batch([db.prepare('INSERT INTO ledger (id,account,amount,kind,ref,created) VALUES (?,?,?,?,?,?)').bind(id(),auth.account,-reward,'reserve',bounty,created),db.prepare('INSERT INTO bounties (id,owner,title,blueprint,entry,reward,status,listed,expires,active_attempt,winner,created,updated) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(bounty,auth.account,title,json(blueprint),money(body.entry),reward,'open',listed?1:0,body.hours?created+body.hours*3600000:null,null,null,created,created),db.prepare('INSERT INTO idempotency (account,key,kind,digest,ref,created) VALUES (?,?,?,?,?,?)').bind(auth.account,key,'create',await hex(json(body)),bounty,created)]);}catch(error){await db.prepare('UPDATE accounts SET balance=balance+? WHERE id=?').bind(reward,auth.account).run();throw error;}
 return bountyView(db,await bountyRow(db,bounty),true);
}

async function settleAttempt(db,attempt,row){
 let result;try{const challenger=parse(attempt.blueprint),defender=parse(row.blueprint),battle=new Battle(unpackChallenge(challenger).machine,unpackChallenge(defender).machine,defender.a,attempt.seed,{mode:'auto',swapSpawns:!!(attempt.seed&1)});result={...battle.run(),seed:attempt.seed};}catch(error){result=null;}
 if(!result||![-1,0,1].includes(result.winner)){await db.batch([db.prepare("UPDATE attempts SET status='refunded',error=?,updated=? WHERE id=?").bind('Simulation unavailable; entry refunded.',now(),attempt.id),db.prepare("UPDATE bounties SET status='open',active_attempt=NULL,updated=? WHERE id=?").bind(now(),row.id)]);await credit(db,attempt.account,row.entry,'refund',attempt.id);return;}
 const quote=rewardQuote(credits(row.reward),credits(row.entry)),win=result.winner===0,receipt={...result,outcome:win?'win':result.winner===1?'loss':'draw',entry:credits(row.entry),grossReward:win?credits(row.reward):0,reward:win?quote.payout:0,payout:win?quote.payout:0,platformFee:win?quote.platformFee:0,platformFeeBps:PLATFORM_FEE_BPS,feePolicyVersion:quote.feePolicyVersion,net:win?quote.netIfWin:-credits(row.entry),verifiedAt:now()};
 if(win){await db.batch([db.prepare("UPDATE attempts SET status='settled',result=?,updated=? WHERE id=?").bind(json(receipt),now(),attempt.id),db.prepare("UPDATE bounties SET status='claimed',active_attempt=NULL,winner=?,updated=? WHERE id=?").bind(attempt.id,now(),row.id),db.prepare('UPDATE accounts SET balance=balance+? WHERE id=?').bind(money(quote.payout),attempt.account),db.prepare('INSERT INTO ledger (id,account,amount,kind,ref,created) VALUES (?,?,?,?,?,?)').bind(id(),attempt.account,money(quote.payout),'reward',attempt.id,now())]);return;}
 await db.batch([db.prepare("UPDATE attempts SET status='settled',result=?,updated=? WHERE id=?").bind(json(receipt),now(),attempt.id),db.prepare("UPDATE bounties SET status='open',active_attempt=NULL,updated=? WHERE id=?").bind(now(),row.id)]);
}
async function enterBounty(db,auth,bountyId,body,key){
 requireAuth(auth);fields(body,['blueprint','maxEntry','maxPlatformFeeBps','participantName','showAddress']);const identity=participantIdentity(body);const old=await prior(db,auth.account,key,'enter:'+bountyId,body);if(old)return attemptView(db,old,auth.account);
 const row=await bountyRow(db,bountyId);check(auth.account!==row.owner,'You can practice against your own bounty, but cannot claim it.',403);check(row.status==='open','This bounty is busy or closed. No credits were taken.',409);check(!row.expires||row.expires>now(),'This bounty has expired.',409);check(body.maxEntry>=credits(row.entry),'Entry exceeds your quoted maximum.',409);check(body.maxPlatformFeeBps>=PLATFORM_FEE_BPS&&body.maxPlatformFeeBps<=10000,'Platform fee exceeds your accepted maximum.',409);
 const blueprint=canonicalBlueprint(body.blueprint,parse(row.blueprint)),me=await account(db,auth.account);check(me.entryCap===null||credits(row.entry)<=me.entryCap,'Entry exceeds your per-attempt spending cap.',409);check(me.dailyCap===null||me.spentToday+credits(row.entry)<=me.dailyCap,'Your daily entry budget is exhausted.',409);
 const attempt=id(),seedBuffer=new Uint32Array(1);crypto.getRandomValues(seedBuffer);const seed=seedBuffer[0],locked=await db.prepare("UPDATE bounties SET status='busy',active_attempt=?,updated=? WHERE id=? AND status='open'").bind(attempt,now(),row.id).run();check(locked.meta.changes===1,'Another challenger entered first. No credits were taken.',409);
 const debit=await db.prepare('UPDATE accounts SET balance=balance-? WHERE id=? AND balance>=?').bind(row.entry,auth.account,row.entry).run();if(debit.meta.changes!==1){await db.prepare("UPDATE bounties SET status='open',active_attempt=NULL,updated=? WHERE id=? AND active_attempt=?").bind(now(),row.id,attempt).run();fail(409,'Not enough available demo credits for this entry.');}
 try{await db.batch([db.prepare('INSERT INTO ledger (id,account,amount,kind,ref,created) VALUES (?,?,?,?,?,?)').bind(id(),auth.account,-row.entry,'entry',attempt,now()),db.prepare('INSERT INTO attempts (id,bounty,account,blueprint,seed,status,result,error,created,updated,participant_name,show_address) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').bind(attempt,row.id,auth.account,json(blueprint),seed,'running',null,null,now(),now(),identity.participantName,identity.showAddress?1:0),db.prepare('INSERT INTO idempotency (account,key,kind,digest,ref,created) VALUES (?,?,?,?,?,?)').bind(auth.account,key,'enter:'+row.id,await hex(json(body)),attempt,now())]);}catch(error){await db.batch([db.prepare('UPDATE accounts SET balance=balance+? WHERE id=?').bind(row.entry,auth.account),db.prepare("UPDATE bounties SET status='open',active_attempt=NULL,updated=? WHERE id=?").bind(now(),row.id)]);throw error;}
 await settleAttempt(db,{id:attempt,account:auth.account,blueprint:json(blueprint),seed},row);return attemptView(db,attempt,auth.account);
}
async function attemptView(db,attemptId,viewer){const attempt=await db.prepare('SELECT * FROM attempts WHERE id=?').bind(attemptId).first();check(attempt,'Attempt not found.',404);const bounty=await bountyRow(db,attempt.bounty),done=['settled','refunded'].includes(attempt.status);check(done||viewer===attempt.account||viewer===bounty.owner,'This attempt is private while running.',403);const value={id:attempt.id,bounty:attempt.bounty,account:attempt.account,participantName:attempt.participant_name||null,machineName:participantMachineName(attempt.blueprint),addressVisible:attempt.show_address===1,participantAddress:null,economics:rewardQuote(credits(bounty.reward),credits(bounty.entry)),status:attempt.status,created:attempt.created,updated:attempt.updated,result:attempt.result?parse(attempt.result):null,error:attempt.error};if(done)value.replay={challenger:parse(attempt.blueprint),defender:parse(bounty.blueprint),arena:parse(bounty.blueprint).a,seed:attempt.seed,swapSpawns:!!(attempt.seed&1),versions:{hash:CLIENT_ENGINE_HASH}};return value;}

async function lockedBlueprint(db,bountyId){return parse((await bountyRow(db,bountyId)).blueprint);}
async function inspection(db,body){
 fields(body,['blueprint','machine','arena','rules','bountyId']);check(!!body.blueprint!==!!body.machine,'Supply either blueprint or machine.');
 const locked=body.bountyId?await lockedBlueprint(db,body.bountyId):null;
 let packed;if(body.machine){fields(body.machine,['name','paint','accent','glow','pattern','number','finish','front','modules','tactic','target','range','stance']);check(Array.isArray(body.machine.modules)&&body.machine.modules.length<=MAX_MODULES,'Supply at most 243 modules.');for(const module of body.machine.modules)check(PARTS.some(part=>part.id===module.id),'Unknown part ID.');const machine={...clone(PRESETS[0]),...body.machine};packed=packChallenge(machine,locked?.a||body.arena||'foundry',0,locked?.q||normalizeRules(body.rules||DEFAULT_RULES));}else packed=canonicalBlueprint(body.blueprint,locked);
 const challenge=unpackChallenge(packed,true),s=stats(challenge.machine),issues=validate(challenge.machine,challenge.rules),arena=ARENAS.find(item=>item.id===challenge.arena),environment=[...new Set(arena.terrain.map(item=>item.type))].map(type=>{const terrain=arena.terrain.find(item=>item.type===type),surface=terrainAt(arena,terrain.x+terrain.w/2,terrain.y+terrain.h/2,9),profile=environmentProfile(s,arena,surface);return {type,speed:s.speed*arena.friction*profile.traction,grip:profile.grip,generation:s.power*profile.power,cooling:s.cooling*profile.cooling,ambientHeat:profile.heat,environmentDrain:profile.drain};});return {valid:!issues.length,issues,stats:s,rules:challenge.rules,arena:challenge.arena,blueprint:packChallenge(challenge.machine,challenge.arena,0,challenge.rules),machine:challenge.machine,environment,advice:engineeringReport(challenge.machine,challenge.rules,challenge.arena),versions:{hash:CLIENT_ENGINE_HASH}};
}
async function practice(db,body){fields(body,['challenger','defender','bountyId','seed']);check(!!body.defender!==!!body.bountyId,'Supply a defender blueprint for practice.');const locked=body.bountyId?await lockedBlueprint(db,body.bountyId):null,challenger=canonicalBlueprint(body.challenger,locked),defender=locked||canonicalBlueprint(body.defender),seed=body.seed??42;integer(seed,0,4294967295,'Seed');const a=unpackChallenge(challenger),b=unpackChallenge(defender),result={...new Battle(a.machine,b.machine,b.arena,seed,{mode:'auto',swapSpawns:!!(seed&1)}).run(),seed};return {kind:'practice',official:false,creditsChanged:0,versions:{hash:CLIENT_ENGINE_HASH},result};}

const openapi={openapi:'3.1.0',info:{title:'War Machines D1 API',version:'3.0'},paths:{'/rules':{get:{}},'/session':{post:{}},'/bounties':{get:{},post:{}},'/me/builds':{get:{},post:{}}}};
const discovery={name:'War Machines',version:'3.0',mode:'demo',description:'Engineer autonomous machines with your own code or model. Same deterministic game engine as browser players.',base:'/api',openapi:'/api/openapi.json',instructions:'/agents.md',skill:'/skills/war-machines-engineer/SKILL.md',catalog:'/api/rules',payments:{enabled:false,mpp:false,tempoMainnet:false,currency:'demo credits',cashValue:false},authentication:{guest:['catalog','bounties','validation','practice'],account:['create/cancel bounty','official entry','save builds','history'],scheme:'Bearer account or scoped agent key'},invariants:{oneActiveAttemptPerBounty:true,creatorSetsEconomics:true,results:'server generated',practicePays:false,officialSeed:'server chosen'}};
const response=(value,status=200)=>new Response(json(value),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
async function bodyOf(request){const length=Number(request.headers.get('content-length')||0);check(length<=65536,'Request exceeds 64 KiB.',413);check(request.headers.get('content-type')?.split(';')[0]==='application/json','Use application/json.',415);try{return await request.json();}catch{fail(400,'Invalid JSON.');}}

export default {async scheduled(event,env,ctx){ctx.waitUntil((async()=>{const until=Date.now()+50000;do{await runAutomaticSettlement(env);if(Date.now()+5000>=until)break;await new Promise(resolve=>setTimeout(resolve,5000));}while(Date.now()<until);})());},async fetch(request,env,ctx){
 if(env.WM_MODE==='tempo-mainnet')return mainnetFetch(request,env,ctx,serveStaticAsset);
 const url=new URL(request.url),path=url.pathname;
 if(path==='/.well-known/war-machines.json'&&request.method==='GET')return response(discovery);
 if(!path.startsWith('/api/'))return serveStaticAsset(request);
 try{check(env.DB,'D1 storage is unavailable.');const db=env.DB,method=request.method;check(['GET','POST','PATCH','PUT','DELETE'].includes(method),'Method not allowed.',405);if(request.headers.get('origin'))check(new URL(request.headers.get('origin')).origin===url.origin,'Cross-origin API requests are not allowed.',403);const body=['POST','PATCH'].includes(method)?await bodyOf(request):{},auth=await dbAuth(db,request);await expire(db);
  if(path==='/api/rules'&&method==='GET')return response(catalog());if(path==='/api/openapi.json'&&method==='GET')return response(openapi);if(path==='/api/health'&&method==='GET')return response({ok:true,app:'war-machines',mode:'demo',paymentsEnabled:false,engineHash:CLIENT_ENGINE_HASH});
  if(path==='/api/session'&&method==='POST'){fields(body,['name']);const name=text(body.name||'Independent engineer',28,'pilot name'),token=secret(),accountId=id(),created=now();await db.prepare('INSERT INTO accounts (id,token_hash,name,balance,entry_cap,daily_cap,created) VALUES (?,?,?,?,?,?,?)').bind(accountId,await hex(token),name,money(1000),null,null,created).run();await db.prepare('INSERT INTO ledger (id,account,amount,kind,ref,created) VALUES (?,?,?,?,?,?)').bind(id(),accountId,money(1000),'grant',accountId,created).run();return response({token,me:await account(db,accountId)},201);}
  if(path==='/api/blueprints/validate'&&method==='POST')return response(await inspection(db,body));if(path==='/api/practice'&&method==='POST')return response(await practice(db,body));
  if(path==='/api/me'&&method==='GET')return response(await account(db,requireAuth(auth).account));if(path==='/api/me'&&method==='PATCH'){requireOwner(auth);fields(body,['name','entryCap','dailyCap']);const existing=await account(db,auth.account),name=own(body,'name')?text(body.name,28,'pilot name'):existing.name,entryCap=own(body,'entryCap')?body.entryCap:existing.entryCap,dailyCap=own(body,'dailyCap')?body.dailyCap:existing.dailyCap;check(entryCap===null||Number.isSafeInteger(entryCap)&&entryCap>=0,'Invalid entry cap.');check(dailyCap===null||Number.isSafeInteger(dailyCap)&&dailyCap>=0,'Invalid daily cap.');await db.prepare('UPDATE accounts SET name=?,entry_cap=?,daily_cap=? WHERE id=?').bind(name,entryCap===null?null:money(entryCap),dailyCap===null?null:money(dailyCap),auth.account).run();return response(await account(db,auth.account));}
  if(path==='/api/me/ledger'&&method==='GET')return response(await ledger(db,requireAuth(auth).account));if(path==='/api/me/attempts'&&method==='GET'){const rows=await db.prepare('SELECT id FROM attempts WHERE account=? ORDER BY created DESC LIMIT 30').bind(requireAuth(auth).account).all();return response(await Promise.all(rows.results.map(row=>attemptView(db,row.id,auth.account))));}
  if(path==='/api/me/builds'&&method==='GET'){requireOwner(auth);const rows=await db.prepare('SELECT id,name,blueprint,created,updated FROM saved_builds WHERE account=? ORDER BY updated DESC LIMIT 50').bind(auth.account).all();return response(rows.results.map(row=>({...row,blueprint:parse(row.blueprint)})));}
  if(path==='/api/me/builds'&&method==='POST'){requireOwner(auth);fields(body,['name','blueprint']);const key=request.headers.get('idempotency-key'),old=await prior(db,auth.account,key,'save-build',body);if(old){const row=await db.prepare('SELECT id,name,blueprint,created,updated FROM saved_builds WHERE id=? AND account=?').bind(old,auth.account).first();return response({...row,blueprint:parse(row.blueprint)});}const count=await db.prepare('SELECT COUNT(*) AS total FROM saved_builds WHERE account=?').bind(auth.account).first();check(count.total<50,'Build vault is full. Delete a saved build first.',409);const build=id(),saved=now(),blueprint=canonicalBlueprint(body.blueprint);await db.batch([db.prepare('INSERT INTO saved_builds (id,account,name,blueprint,created,updated) VALUES (?,?,?,?,?,?)').bind(build,auth.account,text(body.name,48,'build name'),json(blueprint),saved,saved),db.prepare('INSERT INTO idempotency (account,key,kind,digest,ref,created) VALUES (?,?,?,?,?,?)').bind(auth.account,key,'save-build',await hex(json(body)),build,saved)]);return response({id:build,name:body.name.trim(),blueprint,created:saved,updated:saved},201);}
  let match=path.match(/^\/api\/me\/builds\/([a-f0-9-]{36})$/);if(match&&method==='PATCH'){requireOwner(auth);fields(body,['name','blueprint']);const key=request.headers.get('idempotency-key'),kind='update-build:'+match[1],old=await prior(db,auth.account,key,kind,body);if(old){const row=await db.prepare('SELECT id,name,blueprint,created,updated FROM saved_builds WHERE id=? AND account=?').bind(old,auth.account).first();return response({...row,blueprint:parse(row.blueprint)});}const name=text(body.name,48,'build name'),blueprint=canonicalBlueprint(body.blueprint),updated=now(),result=await db.prepare('UPDATE saved_builds SET name=?,blueprint=?,updated=? WHERE id=? AND account=?').bind(name,json(blueprint),updated,match[1],auth.account).run();check(result.meta.changes===1,'Saved build not found.',404);await remember(db,auth.account,key,kind,body,match[1]);return response({id:match[1],name,blueprint,created:(await db.prepare('SELECT created FROM saved_builds WHERE id=?').bind(match[1]).first()).created,updated});}
  if(match&&method==='DELETE'){requireOwner(auth);const result=await db.prepare('DELETE FROM saved_builds WHERE id=? AND account=?').bind(match[1],auth.account).run();check(result.meta.changes===1,'Saved build not found.',404);return response({deleted:true,id:match[1]});}
  if(path==='/api/me/bookmarks'&&method==='GET'){const rows=await db.prepare('SELECT bounty FROM bookmarks WHERE account=? ORDER BY created DESC LIMIT 200').bind(requireAuth(auth).account).all();return response(await Promise.all(rows.results.map(async row=>bountyView(db,await bountyRow(db,row.bounty),true))));}
  match=path.match(/^\/api\/me\/bookmarks\/([a-f0-9-]{36})$/);if(match&&['PUT','DELETE'].includes(method)){requireAuth(auth);await bountyRow(db,match[1]);if(method==='PUT')await db.prepare('INSERT OR IGNORE INTO bookmarks (account,bounty,created) VALUES (?,?,?)').bind(auth.account,match[1],now()).run();else await db.prepare('DELETE FROM bookmarks WHERE account=? AND bounty=?').bind(auth.account,match[1]).run();return response({saved:method==='PUT',bounty:match[1]});}
  if(path==='/api/agents'&&method==='GET'){requireOwner(auth);const rows=await db.prepare('SELECT id,name,created,revoked FROM agent_keys WHERE account=? ORDER BY created DESC').bind(auth.account).all();return response(rows.results.map(row=>({...row,revoked:!!row.revoked,scopes:['read','create','enter','cancel-own']})));}
  if(path==='/api/agents'&&method==='POST'){requireOwner(auth);fields(body,['name']);const count=await db.prepare('SELECT COUNT(*) AS total FROM agent_keys WHERE account=? AND revoked=0').bind(auth.account).first();check(count.total<8,'Revoke an old agent key first.',409);const token=secret(),agent=id(),created=now();await db.prepare('INSERT INTO agent_keys (id,account,token_hash,name,revoked,created) VALUES (?,?,?,?,0,?)').bind(agent,auth.account,await hex(token),text(body.name,28,'agent name'),created).run();return response({token,id:agent,scopes:['read','create','enter','cancel-own']},201);}
  match=path.match(/^\/api\/agents\/([a-f0-9-]{36})$/);if(match&&method==='DELETE'){requireOwner(auth);await db.prepare('UPDATE agent_keys SET revoked=1 WHERE id=? AND account=?').bind(match[1],auth.account).run();return response({ok:true});}
  if(path==='/api/bounties'&&method==='GET'){const rows=await db.prepare('SELECT * FROM bounties WHERE listed=1 OR owner=? ORDER BY CASE status WHEN \'open\' THEN 0 WHEN \'busy\' THEN 1 ELSE 2 END, created DESC LIMIT 100').bind(auth?.account||'').all();return response(await Promise.all(rows.results.map(row=>bountyView(db,row,false))));}
  if(path==='/api/bounties'&&method==='POST')return response(await createBounty(db,auth,body,request.headers.get('idempotency-key')),201);
  match=path.match(/^\/api\/bounties\/([a-f0-9-]{36})(?:\/(attempts|cancel))?$/);if(match){const [,bountyId,action]=match;if(!action&&method==='GET')return response(await bountyView(db,await bountyRow(db,bountyId),true));if(action==='cancel'&&method==='POST'){requireOwner(auth);const row=await bountyRow(db,bountyId);check(row.owner===auth.account,'Only the creator can close this bounty.',403);check(row.status==='open','An active attempt must finish before this bounty can close.',409);await db.batch([db.prepare('UPDATE accounts SET balance=balance+? WHERE id=?').bind(row.reward,auth.account),db.prepare("UPDATE bounties SET status='cancelled',updated=? WHERE id=?").bind(now(),row.id),db.prepare('INSERT INTO ledger (id,account,amount,kind,ref,created) VALUES (?,?,?,?,?,?)').bind(id(),auth.account,row.reward,'release',row.id,now())]);return response(await bountyView(db,await bountyRow(db,row.id),true));}if(action==='attempts'&&method==='POST')return response(await enterBounty(db,auth,bountyId,body,request.headers.get('idempotency-key')),202);}
  match=path.match(/^\/api\/attempts\/([a-f0-9-]{36})$/);if(match&&method==='GET')return response(await attemptView(db,match[1],auth?.account));
  fail(404,'API route not found.');
 }catch(error){console.error('War Machines API error:',error);return response({error:error.status?error.message:'Server error. Retry with the same idempotency key.'},error.status||500);}
}};
