import * as Mppx from '../../node_modules/mppx/dist/server/Mppx.js';
import {tempo} from '../../node_modules/mppx/dist/tempo/server/Methods.js';
import {createClient,http} from 'viem/tempo';
import {getAddress,recoverMessageAddress} from 'viem';
import {privateKeyToAccount} from 'viem/accounts';
import {ARENAS,DEFAULT_RULES,MAX_MODULES,PARTS,PRESETS,clone,environmentProfile,normalizeRules,packChallenge,stats,terrainAt,unpackChallenge,validate} from '../../dist/data.mjs';
import {Battle} from '../../dist/engine.mjs';
import {engineeringReport} from '../../dist/engineering.mjs';
import {CLIENT_ENGINE_HASH} from '../../dist/release.mjs';
import {PLATFORM_FEE_BPS,PLATFORM_FEE_POLICY} from '../../dist/economy.mjs';
import {PART_GUIDANCE} from '../../dist/part-guidance.mjs';
import {PATH_USD_DECIMALS,PATH_USD_TOKEN,PLATFORM_FEE_RECIPIENT,TEMPO_MAINNET_CHAIN_ID,pathUsdToUnits,payoutQuote,unitsToPathUsd} from './pathusd.mjs';

const now=()=>Date.now(),id=()=>crypto.randomUUID(),json=value=>JSON.stringify(value);
const fail=(status,message)=>{const error=Error(message);error.status=status;throw error;};
const check=(value,message,status=400)=>{if(!value)fail(status,message);return value;};
const own=(value,key)=>Object.prototype.hasOwnProperty.call(value,key);
const fields=(value,allowed)=>{check(value&&typeof value==='object'&&!Array.isArray(value),'Expected a JSON object.');check(Object.keys(value).every(key=>allowed.includes(key)),'Unknown field in request.');};
const integer=(value,min,max,label)=>check(Number.isSafeInteger(value)&&value>=min&&value<=max,`${label} must be a whole number from ${min} to ${max}.`);
const text=(value,max,label)=>{check(typeof value==='string'&&value.trim().length>0&&value.trim().length<=max&&!/[\u0000-\u001f]/.test(value),`Invalid ${label}.`);return value.trim();};
const parse=value=>{try{return JSON.parse(value);}catch{fail(500,'Stored game data is invalid.');}};
const validKey=value=>check(typeof value==='string'&&/^[A-Za-z0-9_-]{16,100}$/.test(value),'Supply a unique Idempotency-Key (16–100 letters, numbers, _ or -).');
const base64url=bytes=>btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const randomSecret=()=>{const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return base64url(bytes);};
const hex=async value=>{const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(byte=>byte.toString(16).padStart(2,'0')).join('');};
const response=(value,status=200,headers={})=>new Response(json(value),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...headers}});
const cookie=(request,name)=>request.headers.get('cookie')?.split(';').map(part=>part.trim()).find(part=>part.startsWith(name+'='))?.slice(name.length+1)||null;

function canonicalBlueprint(input,locked){
 fields(input,['v','n','p','t','g','d','s','a','e','b','q','fr','ac','gl','pt','no','f','m']);
 if(input.q)fields(input.q,['mode','combat','credits','parts','mass','weapons']);
 try{const packed=locked?{...input,a:locked.a,e:0,q:locked.q,b:locked.b}:input;const challenge=unpackChallenge(packed);return packChallenge(challenge.machine,challenge.arena,0,challenge.rules);}catch(error){fail(400,error.message||'Invalid blueprint.');}
}

export function runtimeConfig(env,origin){
 if(env.WM_MODE!=='tempo-mainnet')return {mode:'demo',enabled:false};
 // Do not permit the former server-custody flow to be switched on by configuration. A real-money
 // bounty must call the reviewed on-chain escrow directly; that browser and verifier adapter is
 // intentionally a separate, unfinished release gate.
 return {mode:'tempo-mainnet',enabled:false,reason:'On-chain bounty escrow deployment and direct contract integration are required. The legacy custodial payment route is disabled, so this Site cannot accept Tempo funds.'};
}

function catalog(config){const paid=config.enabled;return {mode:'tempo-mainnet',apiVersion:'3.1-sites-mainnet',discovery:'/.well-known/war-machines.json',openapi:'/api/openapi.json',terrainInfo:Object.fromEntries(ARENAS.flatMap(arena=>arena.terrain).map(terrain=>[terrain.type,terrain])),economics:{platformFee:PLATFORM_FEE_POLICY,creditScale:10**PATH_USD_DECIMALS,amountUnit:'pathUSD',network:{chainId:TEMPO_MAINNET_CHAIN_ID,token:PATH_USD_TOKEN,decimals:PATH_USD_DECIMALS,explorer:'https://explore.tempo.xyz'},maxInteger:1000000000,entryMin:'0.01',rewardMin:'0.01',rewardMustExceedEntry:false,personalCapsDefault:null,hours:{min:0,max:8760,zero:'No expiry'}},guest:['build','save local blueprints','share machines','browse','validate','practice'],loginRequired:['create bounty','enter official trial','save bounty','save account builds','account history'],walletAuth:paid?{enabled:true,siwe:'/api/auth/challenge',verify:'/api/auth/verify'}:'locked',mpp:paid?{enabled:true,method:'tempo',intent:'charge',credentialHeader:'Payment-Authorization'}:'locked',activation:paid?undefined:{ready:false,reason:config.reason},versions:{hash:CLIENT_ENGINE_HASH},startingCredits:0,parts:PARTS.map(part=>({...part,...PART_GUIDANCE[part.id]})),arenas:ARENAS,defaultRules:DEFAULT_RULES,examples:PRESETS.map(machine=>packChallenge(machine,'foundry',0)),rules:{oneActiveAttempt:true,combat:'auto',timeLimitSeconds:100,drawIntegrityThreshold:.025,entryRefund:'Technical failure only',spending:'Entry cap and daily account budget',payments:paid?'Tempo mainnet pathUSD payments through MPP. The winner receives 97.5% of the gross reward; 2.5% goes to the disclosed platform recipient. Payout and refund status are independently reconciled.':'Payments are unavailable until escrow configuration is complete. No demo credits are issued.'}};}

const discovery=config=>({name:'War Machines',version:'3.1',mode:'tempo-mainnet',description:'Engineer autonomous machines with your own code or model. Same deterministic game engine as browser players.',base:'/api',openapi:'/api/openapi.json',instructions:'/agents.md',skill:'/skills/war-machines-engineer/SKILL.md',catalog:'/api/rules',payments:config.enabled?{enabled:true,mpp:true,tempoMainnet:true,currency:'pathUSD',token:PATH_USD_TOKEN,decimals:PATH_USD_DECIMALS,chainId:TEMPO_MAINNET_CHAIN_ID,recipients:[config.escrowRecipient,config.platformRecipient],platformFeeBps:250,payout:'winner receives 97.5% of gross reward'}:{enabled:false,mpp:false,tempoMainnet:true,currency:'pathUSD',cashValue:true,reason:config.reason},authentication:{guest:['catalog','bounties','validation','practice'],account:['create/cancel bounty','official entry','save builds','history'],scheme:'Tempo wallet session'},invariants:{oneActiveAttemptPerBounty:true,creatorSetsEconomics:true,results:'server generated',practicePays:false,officialSeed:'server chosen'}});

const openapi={openapi:'3.1.0',info:{title:'War Machines Tempo mainnet API',version:'3.1'},paths:{'/rules':{get:{}},'/auth/challenge':{post:{}},'/auth/verify':{post:{}},'/bounties':{get:{},post:{}},'/me/builds':{get:{},post:{}}}};

async function bodyOf(request){const length=Number(request.headers.get('content-length')||0);check(length<=65536,'Request exceeds 64 KiB.',413);check(request.headers.get('content-type')?.split(';')[0]==='application/json','Use application/json.',415);try{return await request.json();}catch{fail(400,'Invalid JSON.');}}
async function dbAuth(db,request){
 const raw=request.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(raw){const token=await hex(raw);const row=await db.prepare("SELECT id,account,name,'agent' AS role FROM agent_keys WHERE token_hash=? AND revoked=0").bind(token).first();if(row)return row;}
 const value=cookie(request,'wm_session');if(!value)return null;const token=await hex(value),session=await db.prepare('SELECT account FROM sessions WHERE token_hash=? AND expires>?').bind(token,now()).first();if(!session)return null;const row=await db.prepare('SELECT id,name,payout_address FROM accounts WHERE id=?').bind(session.account).first();return row?{...row,account:row.id,role:'owner'}:null;
}
const requireAuth=auth=>check(auth,'Connect a Tempo wallet for bounty actions. Building and practice are open to guests.',401);
const requireOwner=auth=>check(auth?.role==='owner','Tempo bounty funding and entry require the connected payout wallet.',403);
async function prior(db,account,key,kind,body){validKey(key);const digest=await hex(json(body)),row=await db.prepare('SELECT kind,digest,ref FROM idempotency WHERE account=? AND key=?').bind(account,key).first();if(row){check(row.kind===kind&&row.digest===digest,'That idempotency key was used for a different request.',409);return row.ref;}return null;}
async function remember(db,account,key,kind,body,ref){await db.prepare('INSERT INTO idempotency (account,key,kind,digest,ref,created) VALUES (?,?,?,?,?,?)').bind(account,key,kind,await hex(json(body)),ref,now()).run();}
async function amount(value,label,config,{allowZero=false}={}){try{return pathUsdToUnits(value,{allowZero,maxUnits:config.maxOperationUnits});}catch(error){fail(400,`${label}: ${error.message}`);}}
const display=value=>unitsToPathUsd(value);

async function account(db,accountId){
 const row=await db.prepare('SELECT id,name,payout_address,entry_cap_units,daily_cap_units FROM accounts WHERE id=?').bind(accountId).first();check(row,'Account not found.',404);
 const reserveRows=await db.prepare("SELECT reward_units FROM bounties WHERE owner=? AND status IN ('open','busy') AND reward_units IS NOT NULL").bind(accountId).all();
 const day=new Date(now()).setUTCHours(0,0,0,0),spentRows=await db.prepare("SELECT b.entry_units FROM attempts a JOIN bounties b ON b.id=a.bounty WHERE a.account=? AND a.created>=? AND a.status!='refunded' AND b.entry_units IS NOT NULL").bind(accountId,day).all();
 const sum=rows=>rows.results.reduce((total,item)=>total+BigInt(item.reward_units??item.entry_units??0),0n);
 return {id:row.id,name:row.name,balance:'0',entryCap:row.entry_cap_units===null?null:display(row.entry_cap_units),dailyCap:row.daily_cap_units===null?null:display(row.daily_cap_units),spentToday:display(sum(spentRows)),reserved:display(sum(reserveRows)),mode:'tempo-mainnet',payoutAddress:row.payout_address,identities:[{scheme:'tempo',chain:String(TEMPO_MAINNET_CHAIN_ID),address:row.payout_address}],versions:{hash:CLIENT_ENGINE_HASH}};
}
async function ledger(db,accountId){const rows=await db.prepare('SELECT kind,amount_units,ref,created,status FROM financial_operations WHERE account=? ORDER BY created DESC LIMIT 100').bind(accountId).all();return rows.results.map(row=>({kind:row.kind,amount:display(row.amount_units),ref:row.ref,created:row.created,status:row.status}));}
async function payoutAddress(db,accountId){const row=await db.prepare('SELECT payout_address FROM accounts WHERE id=?').bind(accountId).first();return check(row?.payout_address,'Connect a Tempo payout wallet before funding or entering a bounty.',409);}
async function bountyRow(db,bountyId){const row=await db.prepare('SELECT * FROM bounties WHERE id=?').bind(bountyId).first();return check(row,'Bounty not found.',404);}
async function bountyView(db,row,history=false){
 const owner=await db.prepare('SELECT name FROM accounts WHERE id=?').bind(row.owner).first(),quote=payoutQuote(row.reward_units,row.entry_units,row.platform_fee_bps??PLATFORM_FEE_BPS),count=await db.prepare('SELECT COUNT(*) AS total FROM attempts WHERE bounty=?').bind(row.id).first();
 const value={id:row.id,owner:row.owner,ownerName:owner?.name||'Unknown engineer',title:row.title,blueprint:parse(row.blueprint),entry:display(row.entry_units),reward:display(row.reward_units),...quote,status:row.status,listed:!!row.listed,created:row.created,expires:row.expires||null,links:{share:'/#bounty='+row.id,self:'/api/bounties/'+row.id,attempts:'/api/bounties/'+row.id+'/attempts'},versions:{hash:CLIENT_ENGINE_HASH},compatible:true,activeAttempt:row.active_attempt,attempts:count.total,funded:['open','busy'].includes(row.status)&&row.reserve_units===row.reward_units};
 if(history){const rows=await db.prepare("SELECT id,result,created,updated FROM attempts WHERE bounty=? AND status IN ('settled','refunded') ORDER BY created DESC LIMIT 20").bind(row.id).all();value.history=rows.results.map(attempt=>({id:attempt.id,result:attempt.result?parse(attempt.result):null,created:attempt.created,updated:attempt.updated}));}
 return value;
}
async function recordFinancial(db,{kind,account,ref,amountUnits,recipient,status='requested',providerRef=null}){if(BigInt(amountUnits)<=0n)return null;const record=id();await db.prepare('INSERT OR IGNORE INTO financial_operations (id,kind,account,ref,amount_units,recipient,status,provider_ref,created,updated) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(record,kind,account,ref,String(amountUnits),recipient,status,providerRef,now(),now()).run();return await db.prepare('SELECT * FROM financial_operations WHERE kind=? AND ref=?').bind(kind,ref).first();}
async function outgoing(db,kind,account,ref,units,recipient){return recordFinancial(db,{kind,account,ref,amountUnits:units,recipient,status:'requested'});}

function mppStore(db){return {async get(key){const row=await db.prepare('SELECT value FROM payment_kv WHERE key=?').bind(key).first();return row?parse(row.value):null;},async put(key,value){await db.prepare('INSERT INTO payment_kv (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(key,json(value)).run();},async delete(key){await db.prepare('DELETE FROM payment_kv WHERE key=?').bind(key).run();},async update(key,fn){const current=await this.get(key),change=fn(current);if(change.op==='set')await this.put(key,change.value);if(change.op==='delete')await this.delete(key);return change.result;},async tryClaim(key,expires){const marker=json({type:'mppx:replay',expires});const result=await db.prepare("INSERT INTO payment_kv (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value WHERE CAST(json_extract(payment_kv.value,'$.expires') AS INTEGER)<?").bind(key,marker,now()).run();return result.meta.changes===1;}};}
function gateway(db,config){
 const method=tempo.charge({currency:config.token,decimals:config.decimals,chainId:config.chainId,testnet:false,store:mppStore(db),waitForConfirmation:true,sponsorBudget:false});
 const mppx=Mppx.create({methods:[method],secretKey:config.mppSecret,realm:new URL(config.origin).hostname,requiresAuth:true});
 return async(request,{amountUnits,recipient,operation,description,meta,expires})=>{const handler=mppx.charge({amount:display(amountUnits),recipient,externalId:operation,description,meta,expires:new Date(expires).toISOString()});const result=await handler(request);if(result.status===402)return {paid:false,response:result.challenge};const receipt=result.withReceipt(new Response(null,{status:204}));return {paid:true,receipt:receipt.headers.get('payment-receipt')||null};};
}

async function expire(db){
 const current=now(),holds=await db.prepare("SELECT * FROM payment_holds WHERE status='held' AND expires<=?").bind(current).all();
 for(const hold of holds.results){await db.batch([db.prepare("UPDATE payment_holds SET status='expired',updated=? WHERE id=? AND status='held'").bind(current,hold.id),db.prepare("UPDATE bounties SET status='open',active_attempt=NULL,updated=? WHERE id=? AND active_attempt=?").bind(current,hold.bounty,'hold:'+hold.id)]);}
 const bounties=await db.prepare("SELECT * FROM bounties WHERE status='open' AND expires IS NOT NULL AND expires<=?").bind(current).all();
 for(const bounty of bounties.results){const owner=await payoutAddress(db,bounty.owner);await outgoing(db,'reward-refund',bounty.owner,bounty.id,bounty.reserve_units,owner);await db.prepare("UPDATE bounties SET status='expired',reserve_units='0',updated=? WHERE id=? AND status='open'").bind(current,bounty.id).run();}
}

async function settleAttempt(db,attempt,row){
 let result;try{const challenger=parse(attempt.blueprint),defender=parse(row.blueprint);result={...new Battle(unpackChallenge(challenger).machine,unpackChallenge(defender).machine,defender.a,attempt.seed,{mode:'auto',swapSpawns:!!(attempt.seed&1)}).run(),seed:attempt.seed};}catch{result=null;}
 if(!result||![-1,0,1].includes(result.winner)){const recipient=await payoutAddress(db,attempt.account);await outgoing(db,'entry-refund',attempt.account,attempt.id,row.entry_units,recipient);await db.batch([db.prepare("UPDATE attempts SET status='refunded',error=?,updated=? WHERE id=?").bind('Simulation unavailable; entry refund requested.',now(),attempt.id),db.prepare("UPDATE bounties SET status='open',active_attempt=NULL,updated=? WHERE id=?").bind(now(),row.id)]);return;}
 const quote=payoutQuote(row.reward_units,row.entry_units,row.platform_fee_bps??PLATFORM_FEE_BPS),win=result.winner===0,receipt={...result,outcome:win?'win':result.winner===1?'loss':'draw',entry:display(row.entry_units),grossReward:win?display(row.reward_units):'0',reward:win?quote.payout:'0',payout:win?quote.payout:'0',platformFee:win?quote.platformFee:'0',platformFeeBps:row.platform_fee_bps??PLATFORM_FEE_BPS,feePolicyVersion:quote.feePolicyVersion,net:win?quote.netIfWin:'-'+display(row.entry_units),verifiedAt:now()};
 if(win){const recipient=await payoutAddress(db,attempt.account);await outgoing(db,'winner-payout',attempt.account,attempt.id,quote.payoutUnits,recipient);await outgoing(db,'platform-fee','platform',attempt.id,quote.platformFeeUnits,(await runtimeRecipient(row)).platformRecipient);receipt.payoutStatus='requested';await db.batch([db.prepare("UPDATE attempts SET status='settled',result=?,updated=? WHERE id=?").bind(json(receipt),now(),attempt.id),db.prepare("UPDATE bounties SET status='claimed',active_attempt=NULL,winner=?,reserve_units='0',updated=? WHERE id=?").bind(attempt.id,now(),row.id)]);return;}
 await db.batch([db.prepare("UPDATE attempts SET status='settled',result=?,updated=? WHERE id=?").bind(json(receipt),now(),attempt.id),db.prepare("UPDATE bounties SET status='open',active_attempt=NULL,updated=? WHERE id=?").bind(now(),row.id)]);
}

async function runtimeRecipient(row){return {platformRecipient:row.platform_recipient||getAddress(PLATFORM_FEE_RECIPIENT)};}

async function createBounty(db,request,auth,body,key,config){
 requireOwner(auth);fields(body,['title','blueprint','entry','reward','hours','listed','maxPlatformFeeBps']);const old=await prior(db,auth.account,key,'create',body);if(old)return {paid:true,value:await bountyView(db,await bountyRow(db,old),true)};
 check(body.maxPlatformFeeBps===PLATFORM_FEE_BPS,'Acknowledge the 2.5% winning-reward platform fee with maxPlatformFeeBps: 250.',409);integer(body.hours,0,8760,'Duration');check(typeof body.listed==='boolean','Choose board visibility.');const entry=await amount(body.entry,'Entry',config),reward=await amount(body.reward,'Gross reward',config,{allowZero:false}),blueprint=canonicalBlueprint(body.blueprint),title=text(body.title,70,'bounty title'),count=await db.prepare("SELECT COUNT(*) AS total FROM bounties WHERE owner=? AND status IN ('open','busy','funding')").bind(auth.account).first(),reserves=await db.prepare("SELECT reserve_units FROM bounties WHERE status IN ('open','busy') AND reserve_units IS NOT NULL").all();check(count.total<20,'Close an existing bounty first.',409);check(reserves.results.reduce((total,row)=>total+BigInt(row.reserve_units),0n)+reward<=config.maxOutstandingUnits,'Reward would exceed the configured escrow liability ceiling.',409);
 const digest=await hex(json(body));let hold=await db.prepare("SELECT * FROM payment_holds WHERE account=? AND request_key=? AND digest=? AND purpose='reward-funding' AND status='held' AND expires>?").bind(auth.account,key,digest,now()).first();
 if(!hold){const bounty=id(),created=now(),expires=created+config.quoteTtlMs;await db.prepare("INSERT INTO payment_holds (id,account,bounty,request_key,digest,body,amount_units,purpose,expires,status,provider_ref,created,updated) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(bounty,auth.account,bounty,key,digest,json({title,blueprint,entry:String(entry),reward:String(reward),hours:body.hours,listed:body.listed}),String(reward),'reward-funding',expires,'held',null,created,created).run();hold=await db.prepare('SELECT * FROM payment_holds WHERE id=?').bind(bounty).first();}
 const bounty=hold.bounty,created=hold.created,expires=hold.expires,payment=await gateway(db,config)(request,{amountUnits:hold.amount_units,recipient:config.escrowRecipient,operation:'reward:'+bounty,description:'Fund War Machines bounty reward',meta:{kind:'reward-funding',bounty},expires});if(!payment.paid)return {paid:false,response:payment.response};
 await recordFinancial(db,{kind:'reward-funded',account:auth.account,ref:bounty,amountUnits:hold.amount_units,recipient:config.escrowRecipient,status:'confirmed',providerRef:payment.receipt});
 try{await db.batch([db.prepare('INSERT INTO bounties (id,owner,title,blueprint,entry,reward,status,listed,expires,active_attempt,winner,created,updated,entry_units,reward_units,reserve_units,platform_fee_bps,fee_policy_version,platform_recipient) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(bounty,auth.account,title,json(blueprint),0,0,'open',body.listed?1:0,body.hours?created+body.hours*3600000:null,null,null,created,now(),String(entry),String(reward),String(reward),PLATFORM_FEE_BPS,'pathusd-mainnet-v1',config.platformRecipient),db.prepare("UPDATE payment_holds SET status='accepted',provider_ref=?,updated=? WHERE id=?").bind(payment.receipt,now(),bounty),db.prepare('INSERT INTO idempotency (account,key,kind,digest,ref,created) VALUES (?,?,?,?,?,?)').bind(auth.account,key,'create',await hex(json(body)),bounty,now())]);}catch(error){const refund=await payoutAddress(db,auth.account);await outgoing(db,'reward-refund',auth.account,bounty,reward,refund);await db.prepare("UPDATE payment_holds SET status='refund-required',updated=? WHERE id=?").bind(now(),bounty).run();throw error;}
 return {paid:true,value:await bountyView(db,await bountyRow(db,bounty),true),receipt:payment.receipt};
}

async function enterBounty(db,request,auth,bountyId,body,key,config){
 requireOwner(auth);fields(body,['blueprint','maxEntry','maxPlatformFeeBps']);const previous=await prior(db,auth.account,key,'enter:'+bountyId,body);if(previous)return {paid:true,value:await attemptView(db,previous,auth.account)};
 const row=await bountyRow(db,bountyId);check(auth.account!==row.owner,'You can practice against your own bounty, but cannot claim it.',403);check(row.status==='open','This bounty is busy or closed. No payment was accepted.',409);check(!row.expires||row.expires>now(),'This bounty has expired.',409);const maxEntry=await amount(body.maxEntry,'Maximum entry',config),entry=BigInt(row.entry_units);check(maxEntry>=entry,'Entry exceeds your quoted maximum.',409);check(body.maxPlatformFeeBps>=row.platform_fee_bps&&body.maxPlatformFeeBps<=10000,'Platform fee exceeds your accepted maximum.',409);const blueprint=canonicalBlueprint(body.blueprint,parse(row.blueprint)),me=await account(db,auth.account);if(me.entryCap!==null)check(pathUsdToUnits(me.entryCap)>=entry,'Entry exceeds your per-attempt spending cap.',409);if(me.dailyCap!==null)check(pathUsdToUnits(me.spentToday)+entry<=pathUsdToUnits(me.dailyCap),'Your daily entry budget is exhausted.',409);
 const digest=await hex(json(body)),existing=await db.prepare("SELECT * FROM payment_holds WHERE account=? AND bounty=? AND request_key=? AND digest=? AND status='held' AND expires>?").bind(auth.account,bountyId,key,digest,now()).first();let hold=existing;
 if(!hold){const holdId=id(),expires=now()+config.quoteTtlMs,locked=await db.prepare("UPDATE bounties SET status='busy',active_attempt=?,updated=? WHERE id=? AND status='open'").bind('hold:'+holdId,now(),bountyId).run();check(locked.meta.changes===1,'Another challenger entered first. No payment was accepted.',409);try{await db.prepare("INSERT INTO payment_holds (id,account,bounty,request_key,digest,body,amount_units,purpose,expires,status,provider_ref,created,updated) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(holdId,auth.account,bountyId,key,digest,json({blueprint}),String(entry),'entry',expires,'held',null,now(),now()).run();hold=await db.prepare('SELECT * FROM payment_holds WHERE id=?').bind(holdId).first();}catch(error){await db.prepare("UPDATE bounties SET status='open',active_attempt=NULL,updated=? WHERE id=? AND active_attempt=?").bind(now(),bountyId,'hold:'+holdId).run();throw error;}}
 const payment=await gateway(db,config)(request,{amountUnits:entry,recipient:config.entryRecipient,operation:'entry:'+hold.id,description:'Enter War Machines bounty',meta:{kind:'entry',bounty:bountyId,hold:hold.id},expires:hold.expires});if(!payment.paid)return {paid:false,response:payment.response};
 await recordFinancial(db,{kind:'entry-paid',account:auth.account,ref:hold.id,amountUnits:entry,recipient:config.entryRecipient,status:'confirmed',providerRef:payment.receipt});
 const seedBytes=new Uint32Array(1);crypto.getRandomValues(seedBytes);const attempt=id();try{await db.batch([db.prepare('INSERT INTO attempts (id,bounty,account,blueprint,seed,status,result,error,created,updated) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(attempt,bountyId,auth.account,json(blueprint),seedBytes[0],'running',null,null,now(),now()),db.prepare("UPDATE payment_holds SET status='accepted',provider_ref=?,updated=? WHERE id=?").bind(payment.receipt,now(),hold.id),db.prepare("UPDATE bounties SET active_attempt=?,updated=? WHERE id=? AND active_attempt=?").bind(attempt,now(),bountyId,'hold:'+hold.id),db.prepare('INSERT INTO idempotency (account,key,kind,digest,ref,created) VALUES (?,?,?,?,?,?)').bind(auth.account,key,'enter:'+bountyId,digest,attempt,now())]);}catch(error){const recipient=await payoutAddress(db,auth.account);await outgoing(db,'entry-refund',auth.account,hold.id,entry,recipient);await db.batch([db.prepare("UPDATE payment_holds SET status='refund-required',updated=? WHERE id=?").bind(now(),hold.id),db.prepare("UPDATE bounties SET status='open',active_attempt=NULL,updated=? WHERE id=?").bind(now(),bountyId)]);throw error;}
 await settleAttempt(db,{id:attempt,account:auth.account,blueprint:json(blueprint),seed:seedBytes[0]},row);return {paid:true,value:await attemptView(db,attempt,auth.account),receipt:payment.receipt};
}

async function attemptView(db,attemptId,viewer){const attempt=await db.prepare('SELECT * FROM attempts WHERE id=?').bind(attemptId).first();check(attempt,'Attempt not found.',404);const bounty=await bountyRow(db,attempt.bounty),done=['settled','refunded'].includes(attempt.status);check(done||viewer===attempt.account||viewer===bounty.owner,'This attempt is private while running.',403);const value={id:attempt.id,bounty:attempt.bounty,account:attempt.account,economics:payoutQuote(bounty.reward_units,bounty.entry_units,bounty.platform_fee_bps??PLATFORM_FEE_BPS),status:attempt.status,created:attempt.created,updated:attempt.updated,result:attempt.result?parse(attempt.result):null,error:attempt.error};if(done)value.replay={challenger:parse(attempt.blueprint),defender:parse(bounty.blueprint),arena:parse(bounty.blueprint).a,seed:attempt.seed,swapSpawns:!!(attempt.seed&1),versions:{hash:CLIENT_ENGINE_HASH}};const settlement=await db.prepare("SELECT kind,status,provider_ref,updated FROM financial_operations WHERE ref=? AND kind IN ('winner-payout','entry-refund') ORDER BY created DESC LIMIT 1").bind(attempt.id).first();if(settlement)value.settlement=settlement;return value;}

async function inspection(db,body){fields(body,['blueprint','machine','arena','rules','bountyId']);check(!!body.blueprint!==!!body.machine,'Supply either blueprint or machine.');const locked=body.bountyId?parse((await bountyRow(db,body.bountyId)).blueprint):null;let packed;if(body.machine){fields(body.machine,['name','paint','accent','glow','pattern','number','finish','front','modules','tactic','target','range','stance']);check(Array.isArray(body.machine.modules)&&body.machine.modules.length<=MAX_MODULES,'Supply at most 243 modules.');for(const module of body.machine.modules)check(PARTS.some(part=>part.id===module.id),'Unknown part ID.');packed=packChallenge({...clone(PRESETS[0]),...body.machine},locked?.a||body.arena||'foundry',0,locked?.q||normalizeRules(body.rules||DEFAULT_RULES));}else packed=canonicalBlueprint(body.blueprint,locked);const challenge=unpackChallenge(packed,true),s=stats(challenge.machine),issues=validate(challenge.machine,challenge.rules),arena=ARENAS.find(item=>item.id===challenge.arena),environment=[...new Set(arena.terrain.map(item=>item.type))].map(type=>{const terrain=arena.terrain.find(item=>item.type===type),surface=terrainAt(arena,terrain.x+terrain.w/2,terrain.y+terrain.h/2,9),profile=environmentProfile(s,arena,surface);return {type,speed:s.speed*arena.friction*profile.traction,grip:profile.grip,generation:s.power*profile.power,cooling:s.cooling*profile.cooling,ambientHeat:profile.heat,environmentDrain:profile.drain};});return {valid:!issues.length,issues,stats:s,rules:challenge.rules,arena:challenge.arena,blueprint:packChallenge(challenge.machine,challenge.arena,0,challenge.rules),machine:challenge.machine,environment,advice:engineeringReport(challenge.machine,challenge.rules,challenge.arena),versions:{hash:CLIENT_ENGINE_HASH}};}
async function practice(db,body){fields(body,['challenger','defender','bountyId','seed']);check(!!body.defender!==!!body.bountyId,'Supply a defender blueprint for practice.');const locked=body.bountyId?parse((await bountyRow(db,body.bountyId)).blueprint):null,challenger=canonicalBlueprint(body.challenger,locked),defender=locked||canonicalBlueprint(body.defender),seed=body.seed??42;integer(seed,0,4294967295,'Seed');const a=unpackChallenge(challenger),b=unpackChallenge(defender),result={...new Battle(a.machine,b.machine,b.arena,seed,{mode:'auto',swapSpawns:!!(seed&1)}).run(),seed};return {kind:'practice',official:false,creditsChanged:0,versions:{hash:CLIENT_ENGINE_HASH},result};}

async function signInChallenge(db,body,origin){fields(body,['chainId']);check(body.chainId===TEMPO_MAINNET_CHAIN_ID,'Use Tempo mainnet (chain 4217).',400);const nonce=randomSecret(),created=now(),expires=created+5*60*1000,message=`War Machines Tempo sign-in\nDomain: ${new URL(origin).host}\nURI: ${origin}\nChain ID: ${TEMPO_MAINNET_CHAIN_ID}\nNonce: ${nonce}\nIssued At: ${new Date(created).toISOString()}\nExpiration Time: ${new Date(expires).toISOString()}`;await db.prepare('INSERT INTO wallet_challenges (id,message_hash,expires,used,created) VALUES (?,?,?,?,?)').bind(id(),await hex(message),expires,0,created).run();return {message};}
async function verifyWallet(db,body){fields(body,['address','message','signature']);const message=text(body.message,1000,'sign-in message'),challenge=await db.prepare('SELECT * FROM wallet_challenges WHERE message_hash=? AND expires>? AND used=0').bind(await hex(message),now()).first();check(challenge,'This sign-in challenge expired. Connect your wallet again.',401);let address;try{address=getAddress(body.address);const recovered=getAddress(await recoverMessageAddress({message,signature:body.signature}));check(recovered===address,'Wallet signature does not match the selected address.',401);}catch(error){if(error.status)throw error;fail(401,'Wallet signature could not be verified.');}const used=await db.prepare('UPDATE wallet_challenges SET used=1 WHERE id=? AND used=0').bind(challenge.id).run();check(used.meta.changes===1,'This sign-in challenge was already used.',409);let identity=await db.prepare("SELECT account FROM identities WHERE scheme='tempo' AND chain=? AND address=?").bind(String(TEMPO_MAINNET_CHAIN_ID),address).first(),accountId=identity?.account;if(!accountId){accountId=id();await db.batch([db.prepare('INSERT INTO accounts (id,token_hash,name,balance,entry_cap,daily_cap,created,payout_address,entry_cap_units,daily_cap_units) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(accountId,'wallet:'+accountId,'Tempo engineer',0,null,null,now(),address,null,null),db.prepare("INSERT INTO identities (scheme,chain,address,account,created) VALUES ('tempo',?,?,?,?)").bind(String(TEMPO_MAINNET_CHAIN_ID),address,accountId,now())]);}else await db.prepare('UPDATE accounts SET payout_address=? WHERE id=?').bind(address,accountId).run();const token=randomSecret(),expires=now()+30*24*60*60*1000;await db.prepare('INSERT INTO sessions (id,token_hash,account,expires,created) VALUES (?,?,?,?,?)').bind(id(),await hex(token),accountId,expires,now()).run();return {me:await account(db,accountId),headers:{'set-cookie':`wm_session=${token}; Path=/api; HttpOnly; Secure; SameSite=Lax; Max-Age=${30*24*60*60}`}};}

async function reconcile(db,config){
 try{const client=createClient({account:config.signer,feeToken:config.token,transport:http(config.rpcUrl)}),submitted=await db.prepare("SELECT * FROM financial_operations WHERE status='submitted' ORDER BY updated ASC LIMIT 4").all();for(const operation of submitted.results){try{const receipt=await client.getTransactionReceipt({hash:operation.provider_ref});if(receipt.status==='success')await db.prepare("UPDATE financial_operations SET status='confirmed',updated=? WHERE id=?").bind(now(),operation.id).run();else await db.prepare("UPDATE financial_operations SET status='failed-needs-reconciliation',updated=? WHERE id=?").bind(now(),operation.id).run();}catch{}}
  const outstanding=await db.prepare("SELECT amount_units FROM financial_operations WHERE status IN ('requested','sending','submitted')").all();if(outstanding.results.reduce((total,row)=>total+BigInt(row.amount_units),0n)>config.maxOutstandingUnits){console.error('War Machines payout queue paused: outstanding liability ceiling reached.');return;}
  const operation=await db.prepare("SELECT * FROM financial_operations f WHERE f.status='requested' AND (f.kind!='platform-fee' OR EXISTS (SELECT 1 FROM financial_operations winner WHERE winner.kind='winner-payout' AND winner.ref=f.ref AND winner.status='confirmed')) ORDER BY f.created ASC LIMIT 1").first();if(!operation)return;const acquired=await db.prepare("UPDATE financial_operations SET status='sending',updated=? WHERE id=? AND status='requested'").bind(now(),operation.id).run();if(acquired.meta.changes!==1)return;try{const tx=await client.token.transfer({token:config.token,to:operation.recipient,amount:BigInt(operation.amount_units)});await db.prepare("UPDATE financial_operations SET status='submitted',provider_ref=?,updated=? WHERE id=?").bind(tx,now(),operation.id).run();}catch{await db.prepare("UPDATE financial_operations SET status='failed-needs-reconciliation',updated=? WHERE id=?").bind(now(),operation.id).run();}
 }catch(error){console.error('War Machines payout reconciliation:',error);}
}

export async function mainnetFetch(request,env,ctx,serveStaticAsset){
 const url=new URL(request.url),path=url.pathname,config=runtimeConfig(env,url.origin);
 if(path==='/.well-known/war-machines.json'&&request.method==='GET')return response(discovery(config));
 if(!path.startsWith('/api/'))return serveStaticAsset(request);
 try{check(env.DB,'D1 storage is unavailable.');const db=env.DB,method=request.method;check(['GET','POST','PATCH','PUT','DELETE'].includes(method),'Method not allowed.',405);if(request.headers.get('origin'))check(new URL(request.headers.get('origin')).origin===url.origin,'Cross-origin API requests are not allowed.',403);const body=['POST','PATCH'].includes(method)?await bodyOf(request):{},auth=await dbAuth(db,request);
  if(path==='/api/rules'&&method==='GET')return response(catalog(config));if(path==='/api/openapi.json'&&method==='GET')return response(openapi);if(path==='/api/health'&&method==='GET')return response({ok:true,app:'war-machines',mode:'tempo-mainnet',paymentsEnabled:config.enabled,activation:config.enabled?'ready':'locked',engineHash:CLIENT_ENGINE_HASH});if(path==='/api/blueprints/validate'&&method==='POST')return response(await inspection(db,body));if(path==='/api/practice'&&method==='POST')return response(await practice(db,body));
  if(path==='/api/auth/challenge'&&method==='POST')return response(await signInChallenge(db,body,url.origin));if(path==='/api/auth/verify'&&method==='POST'){const verified=await verifyWallet(db,body);return response({me:verified.me},200,verified.headers);}if(path==='/api/auth/logout'&&method==='POST'){const value=cookie(request,'wm_session');if(value)await db.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await hex(value)).run();return response({ok:true},200,{'set-cookie':'wm_session=; Path=/api; HttpOnly; Secure; SameSite=Lax; Max-Age=0'});}
  check(config.enabled,config.reason||'Mainnet payments are unavailable.',503);await expire(db);if(ctx?.waitUntil)ctx.waitUntil(reconcile(db,config));
  if(path==='/api/me'&&method==='GET')return response(await account(db,requireAuth(auth).account));if(path==='/api/me'&&method==='PATCH'){requireOwner(auth);fields(body,['name','entryCap','dailyCap']);const existing=await account(db,auth.account),entryCap=own(body,'entryCap')?body.entryCap:existing.entryCap,dailyCap=own(body,'dailyCap')?body.dailyCap:existing.dailyCap;let entryUnits=null,dailyUnits=null;try{entryUnits=entryCap===null?null:pathUsdToUnits(entryCap);dailyUnits=dailyCap===null?null:pathUsdToUnits(dailyCap);}catch(error){fail(400,error.message);}await db.prepare('UPDATE accounts SET name=?,entry_cap_units=?,daily_cap_units=? WHERE id=?').bind(own(body,'name')?text(body.name,28,'pilot name'):existing.name,entryUnits===null?null:String(entryUnits),dailyUnits===null?null:String(dailyUnits),auth.account).run();return response(await account(db,auth.account));}
  if(path==='/api/me/ledger'&&method==='GET')return response(await ledger(db,requireAuth(auth).account));if(path==='/api/me/attempts'&&method==='GET'){const rows=await db.prepare('SELECT id FROM attempts WHERE account=? ORDER BY created DESC LIMIT 30').bind(requireAuth(auth).account).all();return response(await Promise.all(rows.results.map(row=>attemptView(db,row.id,auth.account))));}
  if(path==='/api/me/builds'&&method==='GET'){requireOwner(auth);const rows=await db.prepare('SELECT id,name,blueprint,created,updated FROM saved_builds WHERE account=? ORDER BY updated DESC LIMIT 50').bind(auth.account).all();return response(rows.results.map(row=>({...row,blueprint:parse(row.blueprint)})));}
  if(path==='/api/me/builds'&&method==='POST'){requireOwner(auth);fields(body,['name','blueprint']);const key=request.headers.get('idempotency-key'),old=await prior(db,auth.account,key,'save-build',body);if(old){const row=await db.prepare('SELECT id,name,blueprint,created,updated FROM saved_builds WHERE id=? AND account=?').bind(old,auth.account).first();return response({...row,blueprint:parse(row.blueprint)});}const count=await db.prepare('SELECT COUNT(*) AS total FROM saved_builds WHERE account=?').bind(auth.account).first();check(count.total<50,'Build vault is full. Delete a saved build first.',409);const build=id(),saved=now(),blueprint=canonicalBlueprint(body.blueprint);await db.batch([db.prepare('INSERT INTO saved_builds (id,account,name,blueprint,created,updated) VALUES (?,?,?,?,?,?)').bind(build,auth.account,text(body.name,48,'build name'),json(blueprint),saved,saved),db.prepare('INSERT INTO idempotency (account,key,kind,digest,ref,created) VALUES (?,?,?,?,?,?)').bind(auth.account,key,'save-build',await hex(json(body)),build,saved)]);return response({id:build,name:body.name.trim(),blueprint,created:saved,updated:saved},201);}
  let match=path.match(/^\/api\/me\/builds\/([a-f0-9-]{36})$/);if(match&&method==='PATCH'){requireOwner(auth);fields(body,['name','blueprint']);const key=request.headers.get('idempotency-key'),kind='update-build:'+match[1],old=await prior(db,auth.account,key,kind,body);if(old){const row=await db.prepare('SELECT id,name,blueprint,created,updated FROM saved_builds WHERE id=? AND account=?').bind(old,auth.account).first();return response({...row,blueprint:parse(row.blueprint)});}const name=text(body.name,48,'build name'),blueprint=canonicalBlueprint(body.blueprint),updated=now(),result=await db.prepare('UPDATE saved_builds SET name=?,blueprint=?,updated=? WHERE id=? AND account=?').bind(name,json(blueprint),updated,match[1],auth.account).run();check(result.meta.changes===1,'Saved build not found.',404);await remember(db,auth.account,key,kind,body,match[1]);return response({id:match[1],name,blueprint,created:(await db.prepare('SELECT created FROM saved_builds WHERE id=?').bind(match[1]).first()).created,updated});}
  if(match&&method==='DELETE'){requireOwner(auth);const result=await db.prepare('DELETE FROM saved_builds WHERE id=? AND account=?').bind(match[1],auth.account).run();check(result.meta.changes===1,'Saved build not found.',404);return response({deleted:true,id:match[1]});}
  if(path==='/api/me/bookmarks'&&method==='GET'){const rows=await db.prepare('SELECT bounty FROM bookmarks WHERE account=? ORDER BY created DESC LIMIT 200').bind(requireAuth(auth).account).all();return response(await Promise.all(rows.results.map(async row=>bountyView(db,await bountyRow(db,row.bounty),true))));}
  match=path.match(/^\/api\/me\/bookmarks\/([a-f0-9-]{36})$/);if(match&&['PUT','DELETE'].includes(method)){requireAuth(auth);await bountyRow(db,match[1]);if(method==='PUT')await db.prepare('INSERT OR IGNORE INTO bookmarks (account,bounty,created) VALUES (?,?,?)').bind(auth.account,match[1],now()).run();else await db.prepare('DELETE FROM bookmarks WHERE account=? AND bounty=?').bind(auth.account,match[1]).run();return response({saved:method==='PUT',bounty:match[1]});}
  if(path==='/api/agents'&&method==='GET'){requireOwner(auth);const rows=await db.prepare('SELECT id,name,created,revoked FROM agent_keys WHERE account=? ORDER BY created DESC').bind(auth.account).all();return response(rows.results.map(row=>({...row,revoked:!!row.revoked,scopes:['read','save-build']})));}
  if(path==='/api/agents'&&method==='POST'){requireOwner(auth);fields(body,['name']);const count=await db.prepare('SELECT COUNT(*) AS total FROM agent_keys WHERE account=? AND revoked=0').bind(auth.account).first();check(count.total<8,'Revoke an old agent key first.',409);const token=randomSecret(),agent=id(),created=now();await db.prepare('INSERT INTO agent_keys (id,account,token_hash,name,revoked,created) VALUES (?,?,?,?,0,?)').bind(agent,auth.account,await hex(token),text(body.name,28,'agent name'),created).run();return response({token,id:agent,scopes:['read','save-build']},201);}
  match=path.match(/^\/api\/agents\/([a-f0-9-]{36})$/);if(match&&method==='DELETE'){requireOwner(auth);await db.prepare('UPDATE agent_keys SET revoked=1 WHERE id=? AND account=?').bind(match[1],auth.account).run();return response({ok:true});}
  if(path==='/api/bounties'&&method==='GET'){const rows=await db.prepare("SELECT * FROM bounties WHERE (listed=1 OR owner=?) AND entry_units IS NOT NULL ORDER BY CASE status WHEN 'open' THEN 0 WHEN 'busy' THEN 1 ELSE 2 END, created DESC LIMIT 100").bind(auth?.account||'').all();return response(await Promise.all(rows.results.map(row=>bountyView(db,row,false))));}
  if(path==='/api/bounties'&&method==='POST'){const result=await createBounty(db,request,auth,body,request.headers.get('idempotency-key'),config);return result.paid?response(result.value,201,result.receipt?{'payment-receipt':result.receipt}:{ }):result.response;}
  match=path.match(/^\/api\/bounties\/([a-f0-9-]{36})(?:\/(attempts|cancel))?$/);if(match){const [,bountyId,action]=match;if(!action&&method==='GET')return response(await bountyView(db,await bountyRow(db,bountyId),true));if(action==='cancel'&&method==='POST'){requireOwner(auth);const row=await bountyRow(db,bountyId);check(row.owner===auth.account,'Only the creator can close this bounty.',403);check(row.status==='open','An active attempt must finish before this bounty can close.',409);const recipient=await payoutAddress(db,auth.account);await outgoing(db,'reward-refund',auth.account,row.id,row.reserve_units,recipient);await db.prepare("UPDATE bounties SET status='cancelled',reserve_units='0',updated=? WHERE id=?").bind(now(),row.id).run();return response(await bountyView(db,await bountyRow(db,row.id),true));}if(action==='attempts'&&method==='POST'){const result=await enterBounty(db,request,auth,bountyId,body,request.headers.get('idempotency-key'),config);return result.paid?response(result.value,202,result.receipt?{'payment-receipt':result.receipt}:{ }):result.response;}}
  match=path.match(/^\/api\/attempts\/([a-f0-9-]{36})$/);if(match&&method==='GET')return response(await attemptView(db,match[1],auth?.account));fail(404,'API route not found.');
 }catch(error){if(!error.status)console.error('War Machines Tempo API error:',error);return response({error:error.status?error.message:'Server error. Retry with the same idempotency key.'},error.status||500);}
}
