import {DatabaseSync} from 'node:sqlite';
import {randomBytes, randomUUID, createHash} from 'node:crypto';
import {CREDIT_SCALE,FEE_POLICY_VERSION,PLATFORM_FEE_BPS,PLATFORM_FEE_POLICY,creditUnits,rewardQuote} from '../dist/economy.mjs';
import {simulationHash} from './simulation-hash.mjs';
import {unpackChallenge, packChallenge, PRESETS, PARTS, ARENAS, DEFAULT_RULES, ENGINE_VERSION, BALANCE_VERSION, TERRAIN_VERSION,TERRAIN_INFO} from '../dist/data.mjs';
import {PART_GUIDANCE} from '../dist/part-guidance.mjs';

export const ENGINE_HASH=simulationHash();
export const MAX_CREDITS=1000000000;
export const versions={engine:ENGINE_VERSION,balance:BALANCE_VERSION,terrain:TERRAIN_VERSION,hash:ENGINE_HASH};
const hash=s=>createHash('sha256').update(s).digest('hex');
const json=JSON.stringify, parse=JSON.parse, id=()=>randomUUID();
export class ApiError extends Error {constructor(status,message){super(message);this.status=status;}}
export function check(ok,message,status=400){if(!ok)throw new ApiError(status,message);}
export function fields(o,keys){check(o&&typeof o==='object'&&!Array.isArray(o),'Expected a JSON object.');check(Object.keys(o).every(k=>keys.includes(k)),'Unknown field in request.');}
const integer=(n,min,max,label)=>{check(Number.isSafeInteger(n)&&n>=min&&n<=max,`${label} must be a whole number from ${min} to ${max}.`);return n;};
const text=(s,max,label)=>{check(typeof s==='string'&&s.trim().length>0&&s.trim().length<=max&&!/[\u0000-\u001f]/.test(s),`Invalid ${label}.`);return s.trim();};
const keyCheck=k=>{check(typeof k==='string'&&/^[A-Za-z0-9_-]{16,100}$/.test(k),'Supply a unique Idempotency-Key (16–100 letters, numbers, _ or -).');return k;};
const bountyQuote=b=>({...rewardQuote(b.reward,b.fee,b.platform_fee_bps),feePolicyVersion:b.fee_policy_version});
export function canonicalBlueprint(input,locked){
 fields(input,['v','n','p','t','g','d','s','a','e','b','q','fr','ac','gl','pt','no','f','m']);
 if(input.q)fields(input.q,['mode','combat','credits','parts','mass','weapons']);
 try{const p=locked?{...input,a:locked.a,e:0,q:locked.q,b:locked.b}:input;const c=unpackChallenge(p);return packChallenge(c.machine,c.arena,0,c.rules);}catch(e){throw new ApiError(400,e.message);}
}

export class Store {
 constructor(path=':memory:',{now=Date.now,seed=true,mode='demo',environment=mode,payment=null}={}){
  this.now=now;this.mode=mode;this.environment=environment;this.payment=payment;this.db=new DatabaseSync(path);this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;
  CREATE TABLE IF NOT EXISTS accounts(id TEXT PRIMARY KEY,name TEXT NOT NULL,balance INTEGER NOT NULL CHECK(balance>=0),entry_cap INTEGER NOT NULL,daily_cap INTEGER NOT NULL,created INTEGER NOT NULL);
  CREATE TABLE IF NOT EXISTS tokens(hash TEXT PRIMARY KEY,account TEXT NOT NULL REFERENCES accounts(id),role TEXT NOT NULL,name TEXT NOT NULL,created INTEGER NOT NULL,revoked INTEGER NOT NULL DEFAULT 0);
  CREATE TABLE IF NOT EXISTS bounties(id TEXT PRIMARY KEY,owner TEXT NOT NULL REFERENCES accounts(id),title TEXT NOT NULL,blueprint TEXT NOT NULL,fee INTEGER NOT NULL,reward INTEGER NOT NULL,status TEXT NOT NULL,listed INTEGER NOT NULL,created INTEGER NOT NULL,expires INTEGER NOT NULL,version TEXT NOT NULL,active TEXT,winning TEXT,reserve INTEGER NOT NULL CHECK(reserve>=0));
  CREATE TABLE IF NOT EXISTS attempts(id TEXT PRIMARY KEY,bounty TEXT NOT NULL REFERENCES bounties(id),account TEXT NOT NULL REFERENCES accounts(id),blueprint TEXT NOT NULL,seed INTEGER NOT NULL,status TEXT NOT NULL,created INTEGER NOT NULL,updated INTEGER NOT NULL,lease TEXT,lease_until INTEGER NOT NULL DEFAULT 0,tries INTEGER NOT NULL DEFAULT 0,result TEXT,error TEXT);
  CREATE UNIQUE INDEX IF NOT EXISTS one_active_attempt ON attempts(bounty) WHERE status IN ('queued','running');
  CREATE INDEX IF NOT EXISTS attempts_queue ON attempts(status,created);
  CREATE TABLE IF NOT EXISTS ledger(id TEXT PRIMARY KEY,account TEXT NOT NULL REFERENCES accounts(id),amount INTEGER NOT NULL,kind TEXT NOT NULL,ref TEXT NOT NULL,created INTEGER NOT NULL,UNIQUE(account,kind,ref));
  CREATE TABLE IF NOT EXISTS operations(account TEXT NOT NULL,key TEXT NOT NULL,kind TEXT NOT NULL,digest TEXT NOT NULL,ref TEXT NOT NULL,PRIMARY KEY(account,key));
   CREATE TABLE IF NOT EXISTS bookmarks(account TEXT NOT NULL REFERENCES accounts(id),bounty TEXT NOT NULL REFERENCES bounties(id),created INTEGER NOT NULL,PRIMARY KEY(account,bounty));
   CREATE TABLE IF NOT EXISTS saved_builds(id TEXT PRIMARY KEY,account TEXT NOT NULL REFERENCES accounts(id),name TEXT NOT NULL,blueprint TEXT NOT NULL,created INTEGER NOT NULL,updated INTEGER NOT NULL);
   CREATE INDEX IF NOT EXISTS saved_builds_owner_updated ON saved_builds(account,updated DESC);
  CREATE TABLE IF NOT EXISTS identities(id TEXT PRIMARY KEY,account TEXT NOT NULL REFERENCES accounts(id),scheme TEXT NOT NULL,chain TEXT NOT NULL,network TEXT NOT NULL,address TEXT,credential TEXT,created INTEGER NOT NULL,verified INTEGER NOT NULL,UNIQUE(scheme,chain,address),UNIQUE(scheme,chain,credential));
  CREATE TABLE IF NOT EXISTS financial_operations(id TEXT PRIMARY KEY,environment TEXT NOT NULL,currency TEXT NOT NULL,kind TEXT NOT NULL,account TEXT,ref TEXT NOT NULL,amount_units TEXT NOT NULL,recipient TEXT NOT NULL,status TEXT NOT NULL,provider_ref TEXT,depends_on TEXT,created INTEGER NOT NULL,updated INTEGER NOT NULL,UNIQUE(environment,kind,ref));
  CREATE TABLE IF NOT EXISTS payment_holds(id TEXT PRIMARY KEY,account TEXT NOT NULL REFERENCES accounts(id),bounty TEXT NOT NULL REFERENCES bounties(id),request_key TEXT NOT NULL,digest TEXT NOT NULL,body TEXT NOT NULL,expires INTEGER NOT NULL,status TEXT NOT NULL,created INTEGER NOT NULL,UNIQUE(account,request_key));
  CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);`);
  // Existing monetary balances keep their value, and existing contracts keep zero platform fee.
  this.tx(()=>{
   const bountyColumns=new Set(this.db.prepare('PRAGMA table_info(bounties)').all().map(c=>c.name));
   if(!bountyColumns.has('platform_fee_bps'))this.db.exec('ALTER TABLE bounties ADD COLUMN platform_fee_bps INTEGER NOT NULL DEFAULT 0 CHECK(platform_fee_bps BETWEEN 0 AND 10000)');
   if(!bountyColumns.has('fee_policy_version'))this.db.exec("ALTER TABLE bounties ADD COLUMN fee_policy_version TEXT NOT NULL DEFAULT 'legacy-no-fee'");
   const tokenColumns=new Set(this.db.prepare('PRAGMA table_info(tokens)').all().map(c=>c.name));
   if(!tokenColumns.has('scopes'))this.db.exec("ALTER TABLE tokens ADD COLUMN scopes TEXT NOT NULL DEFAULT '[\"read\",\"bookmark\",\"create\",\"cancel-own\",\"enter\"]'");
   if(!tokenColumns.has('contracts'))this.db.exec("ALTER TABLE tokens ADD COLUMN contracts TEXT");
   if(!tokenColumns.has('expires'))this.db.exec('ALTER TABLE tokens ADD COLUMN expires INTEGER NOT NULL DEFAULT 0');
   if(!tokenColumns.has('entry_cap'))this.db.exec('ALTER TABLE tokens ADD COLUMN entry_cap INTEGER NOT NULL DEFAULT -1');
   if(!tokenColumns.has('spend_cap'))this.db.exec('ALTER TABLE tokens ADD COLUMN spend_cap INTEGER NOT NULL DEFAULT -1');
   if(!tokenColumns.has('spent'))this.db.exec('ALTER TABLE tokens ADD COLUMN spent INTEGER NOT NULL DEFAULT 0');
   if(!tokenColumns.has('reward_cap'))this.db.exec('ALTER TABLE tokens ADD COLUMN reward_cap INTEGER NOT NULL DEFAULT -1');
   if(!tokenColumns.has('reward_spent'))this.db.exec('ALTER TABLE tokens ADD COLUMN reward_spent INTEGER NOT NULL DEFAULT 0');
   const unit=this.db.prepare('SELECT value FROM meta WHERE key=?').get('credit-scale');
   if(!unit){this.db.exec(`UPDATE accounts SET balance=balance*${CREDIT_SCALE}; UPDATE ledger SET amount=amount*${CREDIT_SCALE}`);this.db.prepare('INSERT INTO meta VALUES (?,?)').run('credit-scale',String(CREDIT_SCALE));}
   else check(unit.value===String(CREDIT_SCALE),'Unsupported ledger unit.',500);
  });
  this.db.prepare("INSERT OR IGNORE INTO accounts VALUES ('platform','Platform fee treasury',0,0,0,?)").run(now());
  this.db.prepare("INSERT OR IGNORE INTO accounts VALUES ('house','Arena treasury',0,0,0,?)").run(now());
  if(seed&&mode==='demo'&&!this.db.prepare('SELECT 1 FROM meta WHERE key=?').get('starter:'+ENGINE_HASH))this.tx(()=>{
   const owner=this.newAccount('Foundry trials',10000).account;
   for(const [i,arena,title] of [[0,'foundry','First contract · Break the Marauder'],[6,'reservoir','Steam test · Firefly'],[1,'quarry','Open a firing lane · Longbow'],[5,'badlands','Crack the Ironclad']])this.create(owner,{title,blueprint:packChallenge(PRESETS[i],arena,0),entry:10,reward:100,maxPlatformFeeBps:PLATFORM_FEE_BPS,hours:168,listed:true},id(),true);
   this.db.prepare('INSERT INTO meta VALUES (?,?)').run('starter:'+ENGINE_HASH,'1');
  });
 }
 close(){this.db.close();}
 tx(fn){this.db.exec('BEGIN IMMEDIATE');try{const result=fn();this.db.exec('COMMIT');return result;}catch(e){this.db.exec('ROLLBACK');throw e;}}
 newAccount(name,grant=this.mode==='demo'?1000:0){
  const account=id(),token=randomBytes(32).toString('base64url'),now=this.now();
  this.db.prepare('INSERT INTO accounts VALUES (?,?,?,?,?,?)').run(account,text(name,28,'pilot name'),0,-1,-1,now);
  this.db.prepare('INSERT INTO tokens (hash,account,role,name,created,revoked) VALUES (?,?,?,?,?,0)').run(hash(token),account,'owner','Browser key',now);
  this.credit(account,grant,'grant',account);return {account,token};
 }
 session(body){fields(body,['name']);return this.tx(()=>{const a=this.newAccount(body.name||'Independent engineer');return {token:a.token,me:this.me(a.account)};});}
 auth(token){check(typeof token==='string'&&token.length>=32,'Create a profile or supply a bearer token.',401);const t=this.db.prepare('SELECT * FROM tokens WHERE hash=? AND revoked=0 AND (expires=0 OR expires>?)').get(hash(token),this.now());check(t,'Invalid, expired or revoked bearer token.',401);return t;}
  owner(auth){check(auth.role==='owner','This action requires the browser owner key.',403);}
 me(account){const a=this.db.prepare('SELECT * FROM accounts WHERE id=?').get(account);const since=new Date(this.now()).setUTCHours(0,0,0,0);const spend=this.db.prepare("SELECT COALESCE(SUM(b.fee),0) AS n FROM attempts a JOIN bounties b ON b.id=a.bounty WHERE a.account=? AND a.status!='refunded' AND a.created>=?").get(account,since).n;return {id:a.id,name:a.name,balance:a.balance/CREDIT_SCALE,entryCap:a.entry_cap<0?null:a.entry_cap,dailyCap:a.daily_cap<0?null:a.daily_cap,spentToday:spend,reserved:this.db.prepare('SELECT COALESCE(SUM(reserve),0) AS n FROM bounties WHERE owner=?').get(account).n,mode:this.mode,identities:this.db.prepare('SELECT scheme,chain,network,address,credential,created,verified FROM identities WHERE account=?').all(account),...{versions}};}
 settings(auth,body){this.owner(auth);fields(body,['name','entryCap','dailyCap']);return this.tx(()=>{const a=this.me(auth.account);this.db.prepare('UPDATE accounts SET name=?,entry_cap=?,daily_cap=? WHERE id=?').run(text(body.name??a.name,28,'pilot name'),(Object.hasOwn(body,'entryCap')?body.entryCap:a.entryCap)===null?-1:integer(body.entryCap??a.entryCap,0,MAX_CREDITS,'Entry cap'),(Object.hasOwn(body,'dailyCap')?body.dailyCap:a.dailyCap)===null?-1:integer(body.dailyCap??a.dailyCap,0,MAX_CREDITS,'Daily cap'),auth.account);return this.me(auth.account);});}
 credit(account,credits,kind,ref){const amount=creditUnits(credits);check(Number.isSafeInteger(amount),'Invalid ledger amount.',500);const exists=this.db.prepare('SELECT amount FROM ledger WHERE account=? AND kind=? AND ref=?').get(account,kind,ref);if(exists){check(exists.amount===amount,'Ledger conflict.',500);return;}const changed=this.db.prepare('UPDATE accounts SET balance=balance+? WHERE id=? AND balance+?>=0 AND balance+?<=9007199254740991').run(amount,account,amount,amount);check(changed.changes===1,'Not enough demo credits.',409);this.db.prepare('INSERT INTO ledger VALUES (?,?,?,?,?,?)').run(id(),account,amount,kind,ref,this.now());}
 ledger(account){return this.db.prepare('SELECT amount,kind,ref,created FROM ledger WHERE account=? ORDER BY created DESC,rowid DESC LIMIT 100').all(account).map(row=>({...row,amount:row.amount/CREDIT_SCALE}));}
 agents(auth,body){this.owner(auth);if(!body)return this.db.prepare("SELECT substr(hash,1,16) AS id,name,created,revoked,scopes,contracts,expires,entry_cap AS entryCap,spend_cap AS spendCap,spent,reward_cap AS rewardCap,reward_spent AS rewardSpent FROM tokens WHERE account=? AND role='agent' ORDER BY created DESC").all(auth.account).map(a=>({...a,scopes:parse(a.scopes),contracts:a.contracts?parse(a.contracts):null,entryCap:a.entryCap<0?null:a.entryCap,spendCap:a.spendCap<0?null:a.spendCap,rewardCap:a.rewardCap<0?null:a.rewardCap}));fields(body,['name','scopes','contracts','expires','entryCap','spendCap','rewardCap']);check(this.agents(auth).filter(a=>!a.revoked).length<8,'Revoke an old agent key first.',409);const allowed=['read','bookmark','create','cancel-own','enter'],scopes=body.scopes??allowed;check(Array.isArray(scopes)&&scopes.length>0&&scopes.every((s,i)=>allowed.includes(s)&&scopes.indexOf(s)===i),'Invalid or duplicate agent scope.');const contracts=body.contracts??null;check(contracts===null||(Array.isArray(contracts)&&contracts.length<=100&&contracts.every(x=>typeof x==='string'&&/^[a-f0-9-]{36}$/.test(x))),'Invalid contract restriction.');const cap=(value,label)=>value===null||value===undefined?-1:integer(value,0,MAX_CREDITS,label),expires=body.expires??0;check(Number.isSafeInteger(expires)&&expires>=0&&(expires===0||expires>this.now()),'Expiry must be a future Unix millisecond timestamp or zero.');const token=randomBytes(32).toString('base64url');this.db.prepare('INSERT INTO tokens (hash,account,role,name,created,revoked,scopes,contracts,expires,entry_cap,spend_cap,reward_cap) VALUES (?,?,?,?,?,0,?,?,?,?,?,?)').run(hash(token),auth.account,'agent',text(body.name,28,'agent name'),this.now(),json(scopes),contracts?json(contracts):null,expires,cap(body.entryCap,'Agent entry cap'),cap(body.spendCap,'Agent cumulative spend cap'),cap(body.rewardCap,'Agent reward-funding cap'));return {token,scopes,contracts,expires,entryCap:body.entryCap??null,spendCap:body.spendCap??null,rewardCap:body.rewardCap??null};}
  revoke(auth,tokenId){this.owner(auth);this.db.prepare("UPDATE tokens SET revoked=1 WHERE account=? AND substr(hash,1,16)=? AND role='agent'").run(auth.account,tokenId);return {ok:true};}
 authorize(auth,scope,{bounty,amount=0,reward=false}={}){if(!auth||auth.role==='owner')return;const scopes=parse(auth.scopes);check(scopes.includes(scope),`Agent key lacks the ${scope} scope.`,403);const contracts=auth.contracts?parse(auth.contracts):null;check(!bounty||contracts===null||contracts.includes(bounty),'Agent key is not authorized for this contract.',403);if(amount){const cap=reward?auth.reward_cap:auth.entry_cap,total=reward?auth.reward_spent:auth.spent;check(cap<0||amount<=cap,reward?'Reward exceeds this agent key funding allowance.':'Entry exceeds this agent key per-entry limit.',403);check(auth.spend_cap<0||auth.spent+auth.reward_spent+amount<=auth.spend_cap,'Agent key cumulative spending limit is exhausted.',403);this.db.prepare(`UPDATE tokens SET ${reward?'reward_spent':'spent'}=${reward?'reward_spent':'spent'}+? WHERE hash=?`).run(amount,auth.hash);}}
 authorizePreview(auth,scope,{bounty,amount=0,reward=false}={}){if(!auth||auth.role==='owner')return;const scopes=parse(auth.scopes);check(scopes.includes(scope),`Agent key lacks the ${scope} scope.`,403);const contracts=auth.contracts?parse(auth.contracts):null;check(!bounty||contracts===null||contracts.includes(bounty),'Agent key is not authorized for this contract.',403);if(amount){const cap=reward?auth.reward_cap:auth.entry_cap;check(cap<0||amount<=cap,reward?'Reward exceeds this agent key funding allowance.':'Entry exceeds this agent key per-entry limit.',403);check(auth.spend_cap<0||auth.spent+auth.reward_spent+amount<=auth.spend_cap,'Agent key cumulative spending limit is exhausted.',403);}}
 identityAccount(scheme,chain,address,credential){return this.db.prepare('SELECT i.account,a.name FROM identities i JOIN accounts a ON a.id=i.account WHERE i.scheme=? AND i.chain=? AND ((? IS NOT NULL AND lower(i.address)=lower(?)) OR (? IS NOT NULL AND i.credential=?))').get(scheme,chain,address,address,credential,credential);}
  provisionIdentity({scheme,chain,network,address=null,credential=null}){check(address||credential,'Verified identity reference required.',500);return this.tx(()=>{const found=this.identityAccount(scheme,chain,address,credential);if(found)return found;const a=this.newAccount(scheme==='tempo'?'Tempo engineer':'Passkey engineer');this.db.prepare('INSERT INTO identities VALUES (?,?,?,?,?,?,?,?,?)').run(id(),a.account,scheme,chain,network,address?.toLowerCase()||null,credential,this.now(),this.now());return {account:a.account,name:scheme==='tempo'?'Tempo engineer':'Passkey engineer'};});}
 attachIdentity(account,{scheme,chain,network,address=null,credential=null}){check(this.db.prepare('SELECT 1 FROM accounts WHERE id=?').get(account),'Account not found.',404);const found=this.identityAccount(scheme,chain,address,credential);check(!found||found.account===account,'That verified identity is already linked to another account.',409);if(!found)this.db.prepare('INSERT INTO identities VALUES (?,?,?,?,?,?,?,?,?)').run(id(),account,scheme,chain,network,address?.toLowerCase()||null,credential,this.now(),this.now());return {account};}
  linkIdentity(auth,identity){this.owner(auth);return this.tx(()=>{const row=this.identityAccount(identity.scheme,identity.chain,identity.address||null,identity.credential||null);check(row,'Verify the wallet or passkey in this session before linking.',401);check(row.account===auth.account||!this.db.prepare('SELECT 1 FROM bounties WHERE owner=? LIMIT 1').get(row.account),'That identity already belongs to another active account.',409);if(row.account!==auth.account){this.db.prepare('UPDATE identities SET account=? WHERE account=? AND scheme=? AND chain=?').run(auth.account,row.account,identity.scheme,identity.chain);}return this.me(auth.account);});}
 payoutAddress(account){const row=this.db.prepare("SELECT address FROM identities WHERE account=? AND scheme='tempo' AND network=? AND address IS NOT NULL ORDER BY verified DESC LIMIT 1").get(account,this.environment);check(row,'A verified Tempo payout address is required for funded operations.',409);return row.address;}
 moneyUnits(amount){const scale=10n**BigInt(this.payment.network.decimals);return (BigInt(creditUnits(amount))*scale/BigInt(CREDIT_SCALE)).toString();}
 financial(kind,account,ref,amountUnits,recipient,status='confirmed',providerRef=null,dependsOn=null){check(this.mode!=='demo','Financial operations are disabled in demo mode.',500);const existing=this.db.prepare('SELECT * FROM financial_operations WHERE environment=? AND kind=? AND ref=?').get(this.environment,kind,ref);if(existing){check(existing.amount_units===String(amountUnits)&&existing.recipient.toLowerCase()===recipient.toLowerCase(),'Financial operation conflict.',500);return existing;}const operation=id(),now=this.now();this.db.prepare('INSERT INTO financial_operations VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(operation,this.environment,this.payment.network.token,kind,account,ref,String(amountUnits),recipient.toLowerCase(),status,providerRef,dependsOn,now,now);return this.db.prepare('SELECT * FROM financial_operations WHERE id=?').get(operation);}
 outgoing(kind,account,ref,amount,recipient,dependsOn=null){if(!amount)return null;const units=this.moneyUnits(amount);check(BigInt(units)<=this.payment.maxOperationUnits,'Financial operation exceeds the configured mainnet ceiling.',500);return this.financial(kind,account,ref,units,recipient,'requested',null,dependsOn);}
 paymentStatus(ref){return this.db.prepare("SELECT id,kind,amount_units AS amountUnits,recipient,status,provider_ref AS providerRef,updated FROM financial_operations WHERE ref=? AND kind IN ('winner-payout','platform-fee','entry-refund','reward-refund') ORDER BY created").all(ref);}
 nextFinancial(){return this.db.prepare("SELECT f.* FROM financial_operations f LEFT JOIN financial_operations d ON d.id=f.depends_on WHERE f.status='requested' AND (f.depends_on IS NULL OR d.status='confirmed') ORDER BY f.created LIMIT 1").get();}
 markFinancial(id,status,providerRef=null){check(['submitted','confirmed','failed-needs-reconciliation'].includes(status),'Invalid financial state.',500);this.db.prepare('UPDATE financial_operations SET status=?,provider_ref=COALESCE(?,provider_ref),updated=? WHERE id=?').run(status,providerRef,this.now(),id);return this.db.prepare('SELECT * FROM financial_operations WHERE id=?').get(id);}
 submittedFinancial(){return this.db.prepare("SELECT * FROM financial_operations WHERE status='submitted' ORDER BY updated LIMIT 20").all();}
 preparePaidAttempt(auth,bounty,body,key,ttlSeconds=180){check(this.mode!=='demo','Paid holds do not exist in demo mode.',500);return this.tx(()=>{fields(body,['blueprint','maxEntry','maxPlatformFeeBps']);keyCheck(key);const digest=hash(json(body)),prior=this.db.prepare('SELECT * FROM payment_holds WHERE account=? AND request_key=?').get(auth.account,key);if(prior){check(prior.bounty===bounty&&prior.digest===digest,'That idempotency key was used for a different request.',409);return prior;}const b=this.rawBounty(bounty),now=this.now();check(b.owner!==auth.account,'You can practice against your own bounty, but cannot claim it.',403);check(b.status==='open','This bounty is busy or closed. No payment was requested.',409);check(!b.expires||b.expires>now,'This bounty has expired.',409);check(parse(b.version).hash===ENGINE_HASH,'This bounty uses an older engine.',409);check(Number.isSafeInteger(body.maxEntry)&&body.maxEntry>=b.fee,'Entry exceeds your quoted maximum.',409);check(Number.isSafeInteger(body.maxPlatformFeeBps)&&body.maxPlatformFeeBps>=b.platform_fee_bps&&body.maxPlatformFeeBps<=10000,'Platform fee exceeds your accepted maximum.',409);canonicalBlueprint(body.blueprint,parse(b.blueprint));check(!this.db.prepare("SELECT 1 FROM payment_holds WHERE account=? AND status='held' AND expires>? LIMIT 1").get(auth.account,now),'Finish or wait for your existing payment quote to expire.',409);const a=this.me(auth.account);check(a.entryCap===null||b.fee<=a.entryCap,'Entry exceeds your per-attempt spending cap.',409);check(a.dailyCap===null||a.spentToday+b.fee<=a.dailyCap,'Your daily entry budget is exhausted.',409);this.authorizePreview(auth,'enter',{bounty,amount:b.fee});const capacity=this.db.prepare("SELECT (SELECT COUNT(*) FROM attempts WHERE status IN ('queued','running'))+(SELECT COUNT(*) FROM payment_holds WHERE status='held' AND expires>?) AS n").get(now).n;check(capacity<16,'Arena queue is full. Try later; no payment was requested.',429);const hold=id(),expires=now+ttlSeconds*1000;this.db.prepare('INSERT INTO payment_holds VALUES (?,?,?,?,?,?,?,?,?)').run(hold,auth.account,bounty,key,digest,json(body),expires,'held',now);this.db.prepare("UPDATE bounties SET status='busy',active=? WHERE id=?").run('hold:'+hold,bounty);return this.db.prepare('SELECT * FROM payment_holds WHERE id=?').get(hold);});}
 prior(account,key,kind,body){keyCheck(key);const op=this.db.prepare('SELECT * FROM operations WHERE account=? AND key=?').get(account,key);if(op)check(op.kind===kind&&op.digest===hash(json(body)),'That idempotency key was used for a different request.',409);return op;}
 operation(account,key,kind,body,ref){this.db.prepare('INSERT INTO operations VALUES (?,?,?,?,?)').run(account,key,kind,hash(json(body)),ref);}
 previewCreate(auth,body,key){const account=auth.account;fields(body,['title','blueprint','entry','reward','hours','listed','maxPlatformFeeBps']);const old=this.prior(account,key,'create',body);if(old)return {prior:old};check(Number.isSafeInteger(body.maxPlatformFeeBps)&&body.maxPlatformFeeBps>=PLATFORM_FEE_BPS&&body.maxPlatformFeeBps<=10000,'Acknowledge the 2.5% winning-reward platform fee with maxPlatformFeeBps (250 basis points).',409);canonicalBlueprint(body.blueprint);text(body.title,70,'bounty title');integer(body.entry,0,MAX_CREDITS,'Entry');const reward=integer(body.reward,0,MAX_CREDITS,'Reward');integer(body.hours,0,8760,'Duration');check(typeof body.listed==='boolean','Choose board visibility.');this.authorizePreview(auth,'create',{amount:reward,reward:true});check(this.db.prepare("SELECT COUNT(*) AS n FROM bounties WHERE owner=? AND status IN ('open','busy')").get(account).n<20,'Close an existing bounty first.',409);if(this.mode!=='demo'){this.payoutAddress(account);check(BigInt(this.moneyUnits(reward))<=this.payment.maxOperationUnits,'Reward exceeds the configured mainnet operation ceiling.',409);}return {reward};}
 create(actor,body,key,nested=false,paymentRef=null){const account=typeof actor==='string'?actor:actor.account;const fn=()=>{
  fields(body,['title','blueprint','entry','reward','hours','listed','maxPlatformFeeBps']);const old=this.prior(account,key,'create',body);if(old)return this.bounty(old.ref);
  check(Number.isSafeInteger(body.maxPlatformFeeBps)&&body.maxPlatformFeeBps>=PLATFORM_FEE_BPS&&body.maxPlatformFeeBps<=10000,'Acknowledge the 2.5% winning-reward platform fee with maxPlatformFeeBps (250 basis points).',409);
  const blueprint=canonicalBlueprint(body.blueprint),title=text(body.title,70,'bounty title'),fee=integer(body.entry,0,MAX_CREDITS,'Entry'),reward=integer(body.reward,0,MAX_CREDITS,'Reward'),hours=integer(body.hours,0,8760,'Duration');check(typeof body.listed==='boolean','Choose board visibility.');
  this.authorize(typeof actor==='string'?null:actor,'create',{amount:reward,reward:true});
  check(this.db.prepare("SELECT COUNT(*) AS n FROM bounties WHERE owner=? AND status IN ('open','busy')").get(account).n<20,'Close an existing bounty first.',409);
  const bounty=id(),now=this.now();if(this.mode==='demo')this.credit(account,-reward,'reserve',bounty);else{check(paymentRef,'Confirmed reward funding proof is required.',402);this.payoutAddress(account);const rewardUnits=this.moneyUnits(reward);check(BigInt(rewardUnits)<=this.payment.maxOperationUnits,'Reward exceeds the configured mainnet operation ceiling.',409);this.financial('reward-funded',account,bounty,rewardUnits,this.payment.escrowRecipient,'confirmed',paymentRef);}
  this.db.prepare('INSERT INTO bounties (id,owner,title,blueprint,fee,reward,status,listed,created,expires,version,active,winning,reserve,platform_fee_bps,fee_policy_version) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(bounty,account,title,json(blueprint),fee,reward,'open',+body.listed,now,hours?now+hours*3600000:0,json(versions),null,null,reward,PLATFORM_FEE_BPS,FEE_POLICY_VERSION);
  this.operation(account,key,'create',body,bounty);return this.bounty(bounty);
 };return nested?fn():this.tx(fn);}
 rawBounty(id){const b=this.db.prepare('SELECT * FROM bounties WHERE id=?').get(id);check(b,'Bounty not found.',404);return b;}
 bounty(id){const b=this.rawBounty(id);return {id:b.id,owner:b.owner,ownerName:this.db.prepare('SELECT name FROM accounts WHERE id=?').get(b.owner).name,title:b.title,blueprint:parse(b.blueprint),entry:b.fee,reward:b.reward,...bountyQuote(b),status:b.status,listed:!!b.listed,created:b.created,expires:b.expires||null,links:{share:'/#bounty='+b.id,self:'/api/bounties/'+b.id,attempts:'/api/bounties/'+b.id+'/attempts'},versions:parse(b.version),compatible:parse(b.version).hash===ENGINE_HASH,activeAttempt:b.active,winningAttempt:b.winning,funded:['open','busy'].includes(b.status)&&b.reserve===b.reward,attempts:this.db.prepare('SELECT COUNT(*) AS n FROM attempts WHERE bounty=?').get(id).n,history:this.db.prepare("SELECT id,status,created,result FROM attempts WHERE bounty=? AND status IN ('settled','refunded') ORDER BY created DESC LIMIT 12").all(id).map(r=>({...r,result:r.result?parse(r.result):null}))};}
 list(account){return this.db.prepare('SELECT id FROM bounties WHERE listed=1 OR owner=? ORDER BY CASE status WHEN \'open\' THEN 0 WHEN \'busy\' THEN 1 ELSE 2 END, created DESC LIMIT 100').all(account||'').map(b=>this.bounty(b.id));}
 closeBounty(b,status){check(!b.active,'An accepted attempt must finish before this bounty can close.',409);if(b.reserve){if(this.mode==='demo')this.credit(b.owner,b.reserve,'release',b.id);else this.outgoing('reward-refund',b.owner,b.id,b.reserve,this.payoutAddress(b.owner));}this.db.prepare('UPDATE bounties SET status=?,reserve=0 WHERE id=?').run(status,b.id);}
 cancel(auth,bounty){return this.tx(()=>{this.authorize(auth,'cancel-own',{bounty});const b=this.rawBounty(bounty);check(b.owner===auth.account,'Only the creator can close this bounty.',403);if(['open','busy'].includes(b.status))this.closeBounty(b,'cancelled');return this.bounty(bounty);});}
 expire(){return this.tx(()=>{for(const hold of this.db.prepare("SELECT * FROM payment_holds WHERE status='held' AND expires<=?").all(this.now())){this.db.prepare("UPDATE payment_holds SET status='expired' WHERE id=?").run(hold.id);const b=this.rawBounty(hold.bounty);if(b.active==='hold:'+hold.id)this.db.prepare("UPDATE bounties SET status='open',active=NULL WHERE id=?").run(b.id);}for(const b of this.db.prepare("SELECT * FROM bounties WHERE status='open'").all())if(b.expires&&b.expires<=this.now())this.closeBounty(b,'expired');else if(parse(b.version).hash!==ENGINE_HASH)this.closeBounty(b,'archived');});}
 accept(actor,bounty,body,key){check(this.mode==='demo','Tempo mainnet entries must complete the MPP quote flow.',500);const account=typeof actor==='string'?actor:actor.account;return this.tx(()=>{
  fields(body,['blueprint','maxEntry','maxPlatformFeeBps']);const old=this.prior(account,key,'enter:'+bounty,body);if(old)return this.attempt(old.ref,account);
  const b=this.rawBounty(bounty);check(b.owner!==account,'You can practice against your own bounty, but cannot claim it.',403);check(b.status==='open','This bounty is busy or closed. No credits were taken.',409);check(!b.expires||b.expires>this.now(),'This bounty has expired.',409);check(parse(b.version).hash===ENGINE_HASH,'This bounty uses an older engine. Its creator can close it and reclaim the reward.',409);
  check(Number.isSafeInteger(body.maxEntry)&&body.maxEntry>=b.fee,'Entry exceeds your quoted maximum.',409);
  check((body.maxPlatformFeeBps===undefined&&b.platform_fee_bps===0)||(Number.isSafeInteger(body.maxPlatformFeeBps)&&body.maxPlatformFeeBps>=b.platform_fee_bps&&body.maxPlatformFeeBps<=10000),'Platform fee exceeds your accepted maximum. Read the contract and send maxPlatformFeeBps before entering.',409);
  this.authorize(typeof actor==='string'?null:actor,'enter',{bounty,amount:b.fee});
  const blueprint=canonicalBlueprint(body.blueprint,parse(b.blueprint)),a=this.me(account);
  check(a.entryCap===null||b.fee<=a.entryCap,'Entry exceeds your per-attempt spending cap.',409);check(a.dailyCap===null||a.spentToday+b.fee<=a.dailyCap,'Your daily entry budget is exhausted.',409);check(this.db.prepare("SELECT COUNT(*) AS n FROM attempts WHERE status IN ('queued','running')").get().n<16,'Arena queue is full. Try later; no credits taken.',429);
  const attempt=id(),now=this.now(),seed=randomBytes(4).readUInt32LE();this.credit(account,-b.fee,'entry',attempt);this.credit('house',b.fee,'entry-income',attempt);
  this.db.prepare('INSERT INTO attempts VALUES (?,?,?,?,?,?,?,?,?,?,?,NULL,NULL)').run(attempt,bounty,account,json(blueprint),seed,'queued',now,now,null,0,0);
  this.db.prepare("UPDATE bounties SET status='busy',active=? WHERE id=?").run(attempt,bounty);this.operation(account,key,'enter:'+bounty,body,attempt);return this.attempt(attempt,account);
 });}
 acceptPaidAttempt(auth,holdId,paymentRef){check(this.mode!=='demo','Paid acceptance is disabled in demo mode.',500);return this.tx(()=>{const hold=this.db.prepare('SELECT * FROM payment_holds WHERE id=? AND account=?').get(holdId,auth.account);check(hold&&hold.status==='held','Payment quote is not active.',409);const b=this.rawBounty(hold.bounty),body=parse(hold.body),now=this.now();const refund=reason=>{this.financial('entry-paid',auth.account,hold.id,this.moneyUnits(b.fee),this.payment.entryRecipient,'confirmed',paymentRef);this.db.prepare("UPDATE payment_holds SET status='refund-required' WHERE id=?").run(hold.id);if(b.active==='hold:'+hold.id)this.db.prepare("UPDATE bounties SET status='open',active=NULL WHERE id=?").run(b.id);this.outgoing('entry-refund',auth.account,hold.id,b.fee,this.payoutAddress(auth.account));return {accepted:false,refundRequired:true,hold:hold.id,status:'refund-required',reason};};if(hold.expires<=now)return refund('Payment arrived after the quote expired.');if(b.status!=='busy'||b.active!=='hold:'+hold.id)return refund('The bounty hold was not preserved.');let blueprint;try{blueprint=canonicalBlueprint(body.blueprint,parse(b.blueprint));const a=this.me(auth.account);check(a.entryCap===null||b.fee<=a.entryCap,'Entry now exceeds your per-attempt spending cap.',409);check(a.dailyCap===null||a.spentToday+b.fee<=a.dailyCap,'Your daily entry budget is now exhausted.',409);check(this.db.prepare("SELECT COUNT(*) AS n FROM attempts WHERE status IN ('queued','running')").get().n<16,'The arena queue filled before payment confirmation.',429);this.authorizePreview(auth,'enter',{bounty:b.id,amount:b.fee});}catch(e){if(e instanceof ApiError)return refund(e.message);throw e;}this.financial('entry-paid',auth.account,hold.id,this.moneyUnits(b.fee),this.payment.entryRecipient,'confirmed',paymentRef);this.authorize(auth,'enter',{bounty:b.id,amount:b.fee});const attempt=id(),seed=randomBytes(4).readUInt32LE();this.db.prepare('INSERT INTO attempts VALUES (?,?,?,?,?,?,?,?,?,?,?,NULL,NULL)').run(attempt,b.id,auth.account,json(blueprint),seed,'queued',now,now,null,0,0);this.db.prepare("UPDATE bounties SET active=? WHERE id=?").run(attempt,b.id);this.db.prepare("UPDATE payment_holds SET status='accepted' WHERE id=?").run(hold.id);this.operation(auth.account,hold.request_key,'enter:'+b.id,body,attempt);return {accepted:true,attempt:this.attempt(attempt,auth.account)};});}
 attempt(id,account){const a=this.db.prepare('SELECT * FROM attempts WHERE id=?').get(id);check(a,'Attempt not found.',404);const b=this.rawBounty(a.bounty),done=['settled','refunded'].includes(a.status);check(done||account===a.account||account===b.owner,'This attempt is still private while running.',403);return {id:a.id,bounty:a.bounty,account:a.account,economics:bountyQuote(b),status:a.status,created:a.created,updated:a.updated,result:a.result?parse(a.result):null,error:a.error,...(this.mode==='demo'?{}:{settlement:this.paymentStatus(a.id)}),...(done?{replay:{challenger:parse(a.blueprint),defender:parse(b.blueprint),arena:parse(b.blueprint).a,seed:a.seed,swapSpawns:!!(a.seed&1),versions:parse(b.version)}}:{})};}
 claim(){return this.tx(()=>{
  const a=this.db.prepare("SELECT * FROM attempts WHERE status='queued' OR (status='running' AND lease_until<?) ORDER BY created LIMIT 1").get(this.now());if(!a)return null;
  const b=this.rawBounty(a.bounty);if(a.tries>=3||parse(b.version).hash!==ENGINE_HASH){this.refund(a,b,'Simulation unavailable; entry refunded.');return null;}
  const lease=id();this.db.prepare("UPDATE attempts SET status='running',lease=?,lease_until=?,tries=tries+1,updated=? WHERE id=?").run(lease,this.now()+45000,this.now(),a.id);
  return {id:a.id,lease,challenger:parse(a.blueprint),defender:parse(b.blueprint),arena:parse(b.blueprint).a,seed:a.seed,swapSpawns:!!(a.seed&1),engineHash:ENGINE_HASH};
 });}
 refund(a,b,error){if(this.mode==='demo'){this.credit('house',-b.fee,'refund-out',a.id);this.credit(a.account,b.fee,'refund',a.id);}else this.outgoing('entry-refund',a.account,a.id,b.fee,this.payoutAddress(a.account));this.db.prepare("UPDATE attempts SET status='refunded',error=?,updated=?,lease=NULL WHERE id=?").run(error,this.now(),a.id);this.reopen(b);}
 reopen(b){this.db.prepare("UPDATE bounties SET status='open',active=NULL WHERE id=?").run(b.id);if(b.expires&&b.expires<=this.now())this.closeBounty({...b,active:null},'expired');}
 finish(job,result,error){return this.tx(()=>{
  const a=this.db.prepare('SELECT * FROM attempts WHERE id=?').get(job.id);if(!a||a.status!=='running'||a.lease!==job.lease)return false;const b=this.rawBounty(a.bounty);
  if(error){this.refund(a,b,error);return true;}
  check(result&&[-1,0,1].includes(result.winner)&&Number.isFinite(result.time)&&result.time>=2&&result.time<=101&&result.seed===a.seed,'Invalid worker result.',500);
  const quote=bountyQuote(b),win=result.winner===0;
  const receipt={...result,outcome:win?'win':result.winner===1?'loss':'draw',entry:b.fee,grossReward:win?b.reward:0,reward:win?quote.payout:0,payout:win?quote.payout:0,platformFee:win?quote.platformFee:0,platformFeeBps:b.platform_fee_bps,feePolicyVersion:quote.feePolicyVersion,net:win?quote.netIfWin:-b.fee,verifiedAt:this.now()};
  this.db.prepare("UPDATE attempts SET status='settled',result=?,updated=?,lease=NULL WHERE id=?").run(json(receipt),this.now(),a.id);
  if(result.winner===0){if(this.mode==='demo'){this.credit(a.account,quote.payout,'reward',a.id);if(quote.platformFee)this.credit('platform',quote.platformFee,'platform-fee',a.id);}else{const winner=this.outgoing('winner-payout',a.account,a.id,quote.payout,this.payoutAddress(a.account));this.outgoing('platform-fee','platform',a.id,quote.platformFee,this.payment.platformRecipient,winner?.id||null);receipt.payoutStatus='requested';this.db.prepare('UPDATE attempts SET result=? WHERE id=?').run(json(receipt),a.id);}this.db.prepare("UPDATE bounties SET status='claimed',reserve=0,active=NULL,winning=? WHERE id=?").run(a.id,b.id);}else this.reopen(b);return true;
 });}
  bookmarks(account){return this.db.prepare('SELECT bounty FROM bookmarks WHERE account=? ORDER BY created DESC LIMIT 200').all(account).map(r=>this.bounty(r.bounty));}
  builds(auth){this.owner(auth);return this.db.prepare('SELECT id,name,blueprint,created,updated FROM saved_builds WHERE account=? ORDER BY updated DESC LIMIT 50').all(auth.account).map(row=>({...row,blueprint:parse(row.blueprint)}));}
  build(id,account){const row=this.db.prepare('SELECT id,name,blueprint,created,updated FROM saved_builds WHERE id=? AND account=?').get(id,account);check(row,'Saved build not found.',404);return {...row,blueprint:parse(row.blueprint)};}
  saveBuild(auth,body,key){this.owner(auth);fields(body,['name','blueprint']);const old=this.prior(auth.account,key,'save-build',body);if(old)return this.build(old.ref,auth.account);const name=text(body.name,48,'build name'),blueprint=canonicalBlueprint(body.blueprint);return this.tx(()=>{check(this.db.prepare('SELECT COUNT(*) AS n FROM saved_builds WHERE account=?').get(auth.account).n<50,'Build vault is full. Delete a saved build first.',409);const build=id(),now=this.now();this.db.prepare('INSERT INTO saved_builds VALUES (?,?,?,?,?,?)').run(build,auth.account,name,json(blueprint),now,now);this.operation(auth.account,key,'save-build',body,build);return this.build(build,auth.account);});}
  updateBuild(auth,build,body,key){this.owner(auth);fields(body,['name','blueprint']);const old=this.prior(auth.account,key,'update-build:'+build,body);if(old)return this.build(old.ref,auth.account);const name=text(body.name,48,'build name'),blueprint=canonicalBlueprint(body.blueprint);return this.tx(()=>{this.build(build,auth.account);this.db.prepare('UPDATE saved_builds SET name=?,blueprint=?,updated=? WHERE id=? AND account=?').run(name,json(blueprint),this.now(),build,auth.account);this.operation(auth.account,key,'update-build:'+build,body,build);return this.build(build,auth.account);});}
  deleteBuild(auth,build){this.owner(auth);const result=this.db.prepare('DELETE FROM saved_builds WHERE id=? AND account=?').run(build,auth.account);check(result.changes===1,'Saved build not found.',404);return {deleted:true,id:build};}
 bookmark(actor,bounty,save=true){const account=typeof actor==='string'?actor:actor.account;this.authorize(typeof actor==='string'?null:actor,'bookmark',{bounty});this.rawBounty(bounty);if(save)this.db.prepare('INSERT OR IGNORE INTO bookmarks VALUES (?,?,?)').run(account,bounty,this.now());else this.db.prepare('DELETE FROM bookmarks WHERE account=? AND bounty=?').run(account,bounty);return {saved:save,bounty};}
  catalog(){const paid=this.mode!=='demo';return {mode:this.mode,apiVersion:'2.3',discovery:'/.well-known/war-machines.json',openapi:'/api/openapi.json',terrainInfo:TERRAIN_INFO,economics:{platformFee:PLATFORM_FEE_POLICY,creditScale:paid?10**this.payment.network.decimals:CREDIT_SCALE,amountUnit:paid?this.payment.network.currency:'demo credits',network:paid?{chainId:this.payment.network.chainId,token:this.payment.network.token,decimals:this.payment.network.decimals,explorer:this.payment.network.explorer}:null,maxInteger:MAX_CREDITS,entryMin:0,rewardMin:0,rewardMustExceedEntry:false,personalCapsDefault:null,hours:{min:0,max:8760,zero:'No expiry'}},guest:['build','save local blueprints','share machines','browse','validate','practice'],loginRequired:['create bounty','enter official trial','save bounty','save account builds','account history'],walletAuth:paid?{enabled:true,siwe:'/api/auth/challenge',verify:'/api/auth/verify',passkey:'/api/auth/passkey'}:'disabled',mpp:paid?{enabled:true,method:'tempo',intent:'charge',credentialHeader:'Payment-Authorization'}:'disabled',versions,startingCredits:paid?0:1000,parts:PARTS.map(part=>({...part,...PART_GUIDANCE[part.id]})),arenas:ARENAS,defaultRules:DEFAULT_RULES,examples:PRESETS.map(m=>packChallenge(m,'foundry',0)),rules:{oneActiveAttempt:true,combat:'auto',timeLimitSeconds:100,drawIntegrityThreshold:.025,entryRefund:'Technical failure only',spending:'Entry cap, cumulative delegated-agent budget and separate reward-funding allowance',payments:paid?'Tempo mainnet pathUSD through MPP; payout states are reconciled separately.':'Demo only — no wallets, MPP, Tempo or cash value'}};}
}
