// Regenerate after editing simulation or catalog data, before starting a release.
import {writeFileSync} from 'node:fs';
import {simulationHash} from '../server/simulation-hash.mjs';
const hash=simulationHash();
writeFileSync(new URL('../dist/release.mjs',import.meta.url),`// Generated by scripts/stamp-release.mjs. Detects stale browser physics.\nexport const CLIENT_ENGINE_HASH='${hash}';\n`);
console.log('Stamped simulation release '+hash);
