// Read-only release gate. Generation is an explicit, separate command.
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { assertSimulationSourceGraph, hashSimulationSources } from '../server/simulation-hash.mjs';

export function verifyRelease(root = new URL('../', import.meta.url)) {
  const read = path => readFileSync(new URL(path, root), 'utf8');
  const engine = read('dist/engine.mjs');
  const data = read('dist/data.mjs');
  const release = read('dist/release.mjs');
  assertSimulationSourceGraph(engine, data);
  const actual = hashSimulationSources(engine, data);
  const match = release.match(/^\/\/ Generated by scripts\/stamp-release\.mjs\. Detects stale browser physics\.\r?\nexport const CLIENT_ENGINE_HASH='([a-f0-9]{64})';\r?\n$/);
  if (!match) throw Error('Malformed simulation release stamp. Run node scripts/stamp-release.mjs explicitly.');
  if (match[1] !== actual) throw Error(`Stale simulation release stamp: advertised ${match[1]}, sources ${actual}. Run node scripts/stamp-release.mjs explicitly after engine edits are final.`);
  return actual;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  try { console.log('Verified simulation release ' + verifyRelease()); }
  catch (error) { console.error(error.message); process.exitCode = 1; }
}
